-- Migration 021: Backfill all app strings with English and French values.
-- Uses ON CONFLICT ... DO UPDATE so this is safe to re-run.
-- Strings with {{variable}} use double-brace interpolation syntax.

INSERT INTO public.app_strings (string_key, category, en, fr, context_note, max_chars) VALUES

-- ─── AUTH (14 strings) ────────────────────────────────────────────────────────
('auth.login_title',       'auth', 'Log in',              'Connexion',               'Title on login screen', 20),
('auth.register_title',    'auth', 'Create account',      'Créer un compte',         'Title on register screen', 25),
('auth.email',             'auth', 'Email',               'E-mail',                  'Email field label', 15),
('auth.password',          'auth', 'Password',            'Mot de passe',            'Password field label', 15),
('auth.display_name',      'auth', 'Display name',        'Nom affiché',             'Display name field label', 20),
('auth.sign_in',           'auth', 'Log in',              'Se connecter',            'Login button', 20),
('auth.sign_up',           'auth', 'Sign up',             'S''inscrire',             'Register button', 20),
('auth.no_account',        'auth', 'No account yet?',     'Pas encore de compte ?',  'Link to register', 30),
('auth.have_account',      'auth', 'Already have an account?', 'Déjà un compte ?',   'Link to login', 30),
('auth.forgot_password',   'auth', 'Forgot password?',   'Mot de passe oublié ?',   'Forgot password link', 25),
('auth.reset_sent',        'auth', 'Reset email sent.',  'E-mail de réinitialisation envoyé.', 'Confirmation after reset', 40),
('auth.confirm_email',     'auth', 'A confirmation email has been sent. Check your inbox then log in.', 'Un e-mail de confirmation vous a été envoyé. Vérifiez votre boîte mail puis connectez-vous.', 'Post-register confirmation', NULL),
('auth.error_invalid',     'auth', 'Invalid email or password.', 'E-mail ou mot de passe invalide.', 'Login error', NULL),
('auth.error_generic',     'auth', 'Something went wrong. Please try again.', 'Une erreur est survenue. Réessayez.', 'Generic auth error', NULL),

-- ─── ONBOARDING (9 strings) ───────────────────────────────────────────────────
('onboarding.select_ll_title',        'onboarding', 'What language do you want to learn?', 'Quelle langue voulez-vous apprendre ?', 'Onboarding language selection title', NULL),
('onboarding.select_ll_sub',          'onboarding', 'Choose your target language.',        'Choisissez votre langue cible.',         'Onboarding language selection subtitle', NULL),
('onboarding.continue',               'onboarding', 'Continue',                            'Continuer',                              'Onboarding continue button', 20),
('onboarding.proficiency_title',      'onboarding', 'What is your level?',                 'Quel est votre niveau ?',                'Proficiency selection title', NULL),
('onboarding.proficiency_sub',        'onboarding', 'Help us personalize your journey.',   'Aidez-nous à personnaliser votre parcours.', 'Proficiency selection subtitle', NULL),
('onboarding.level_beginner_0',       'onboarding', 'Complete beginner',                   'Débutant complet',                       'Level option', 25),
('onboarding.level_beginner_0_desc',  'onboarding', 'I have no prior knowledge',           'Je n''ai aucune connaissance',           'Level option description', NULL),
('onboarding.level_beginner_1',       'onboarding', 'Beginner',                            'Débutant',                               'Level option', 20),
('onboarding.level_beginner_1_desc',  'onboarding', 'I know a few words',                  'Je connais quelques mots',               'Level option description', NULL),
('onboarding.level_intermediate',     'onboarding', 'Intermediate',                        'Intermédiaire',                          'Level option', 20),
('onboarding.level_intermediate_desc','onboarding', 'I can hold a simple conversation',    'Je peux tenir une conversation simple',  'Level option description', NULL),
('onboarding.level_advanced',         'onboarding', 'Advanced',                            'Avancé',                                 'Level option', 20),
('onboarding.level_advanced_desc',    'onboarding', 'I want to perfect my level',          'Je veux perfectionner mon niveau',       'Level option description', NULL),

-- ─── NAVIGATION (8 strings) ───────────────────────────────────────────────────
('nav.home',        'navigation', 'Home',       'Accueil',   'Bottom tab label', 12),
('nav.leaderboard', 'navigation', 'Leaderboard','Classement','Bottom tab label', 14),
('nav.profile',     'navigation', 'Profile',    'Profil',    'Bottom tab label', 12),
('nav.browse',      'navigation', 'Browse',     'Parcourir', 'Bottom tab label', 12),
('nav.shop',        'navigation', 'Shop',       'Boutique',  'Bottom tab label', 12),
('nav.admin',       'navigation', 'Admin',      'Admin',     'Bottom tab label (admin only)', 10),
('nav.back',        'navigation', 'Back',       'Retour',    'Back navigation button', 10),
('nav.close',       'navigation', 'Close',      'Fermer',    'Close/dismiss button', 10),

-- ─── COMMON ACTIONS (8 strings) ───────────────────────────────────────────────
('common.next',      'buttons', 'Next',      'Suivant',    'Next button', 12),
('common.continue',  'buttons', 'Continue',  'Continuer',  'Continue button', 15),
('common.skip',      'buttons', 'Skip',      'Passer',     'Skip button', 10),
('common.try_again', 'buttons', 'Try again', 'Réessayer',  'Retry button', 15),
('common.save',      'buttons', 'Save',      'Enregistrer','Save button', 12),
('common.cancel',    'buttons', 'Cancel',    'Annuler',    'Cancel button', 12),
('common.loading',   'buttons', 'Loading…',  'Chargement…','Loading indicator', 20),
('common.close',     'buttons', 'Close',     'Fermer',     'Close button', 10),

-- ─── BUTTONS (12 strings) ─────────────────────────────────────────────────────
('btn.continue', 'buttons', 'Continue', 'Continuer',  'Continue action', 15),
('btn.next',     'buttons', 'Next',     'Suivant',    'Next action', 12),
('btn.back',     'buttons', 'Back',     'Retour',     'Back action', 10),
('btn.cancel',   'buttons', 'Cancel',   'Annuler',    'Cancel action', 12),
('btn.save',     'buttons', 'Save',     'Sauvegarder','Save action', 12),
('btn.retry',    'buttons', 'Try again','Réessayer',  'Retry action', 15),
('btn.skip',     'buttons', 'Skip',     'Passer',     'Skip action', 10),
('btn.confirm',  'buttons', 'Confirm',  'Confirmer',  'Confirm action', 12),
('btn.done',     'buttons', 'Done',     'Terminé',    'Done/finish action', 10),
('btn.start',    'buttons', 'Start',    'Commencer',  'Start action', 10),
('btn.yes',      'buttons', 'Yes',      'Oui',        'Yes/affirmative', 8),
('btn.no',       'buttons', 'No',       'Non',        'No/negative', 8),

-- ─── ERRORS (10 strings) ──────────────────────────────────────────────────────
('error.generic',         'errors', 'Something went wrong.',             'Quelque chose s''est mal passé.',       'Generic error', NULL),
('error.network',         'errors', 'Connection problem.',               'Problème de connexion.',                'Network error', NULL),
('error.network_retry',   'errors', 'Try again',                         'Réessayer',                             'Retry button for network error', 15),
('error.empty',           'errors', 'Nothing to display.',               'Aucun élément à afficher.',             'Empty data error', NULL),
('error.login_failed',    'errors', 'Incorrect email or password.',       'E-mail ou mot de passe incorrect.',     'Login failure', NULL),
('error.register_failed', 'errors', 'Could not create account.',         'Impossible de créer le compte.',        'Register failure', NULL),
('error.email_taken',     'errors', 'This email is already in use.',     'Cet e-mail est déjà utilisé.',          'Email already registered', NULL),
('error.weak_password',   'errors', 'Password must be at least 6 characters.', 'Le mot de passe doit contenir au moins 6 caractères.', 'Weak password', NULL),
('error.load_lesson',     'errors', 'Could not load the lesson.',        'Impossible de charger la leçon.',       'Lesson load failure', NULL),
('error.save_failed',     'errors', 'Save failed. Try again.',           'Sauvegarde échouée. Réessaye.',         'Save failure', NULL),
('error.session_expired', 'errors', 'Log in again to continue.',         'Reconnecte-toi pour continuer.',        'Session expired', NULL),
('error.image_fallback',  'errors', 'Image unavailable',                 'Image indisponible',                    'Image load failure', 20),

-- ─── LESSON (14 strings) ──────────────────────────────────────────────────────
('lesson.progress',        'lesson', 'Progress',                   'Progression',                     'Lesson progress label', 15),
('lesson.hearts',          'lesson', 'Lives',                      'Vies',                            'Lives/hearts label', 10),
('lesson.correct',         'lesson', 'Correct!',                   'Correct !',                       'Correct answer feedback', 15),
('lesson.wrong',           'lesson', 'Not quite…',                 'Pas tout à fait…',                'Wrong answer feedback', 20),
('lesson.almost',          'lesson', 'Almost! Check your spelling.','Presque ! Vérifie l''orthographe.','Almost-correct feedback', NULL),
('lesson.complete_title',  'lesson', 'Lesson complete!',           'Leçon terminée !',                'Lesson completion title', 25),
('lesson.no_hearts',       'lesson', 'No lives left. Come back later or buy lives.', 'Plus de vies. Revenez plus tard ou achetez des vies.', 'No hearts message', NULL),
('lesson.no_hearts_shop',  'lesson', 'Refill lives',               'Recharge tes vies',               'Buy lives button', 20),
('lesson.no_hearts_review','lesson', 'Review mode',                'Mode révision',                   'Review mode button', 20),
('lesson.locked',          'lesson', 'Locked',                     'Verrouillé',                      'Locked lesson label', 12),
('lesson.loading_patience','lesson', 'Loading your lesson…',       'Chargement de ta leçon…',         'Lesson loading message', NULL),
('lesson.review_mode',     'lesson', 'Review mode',                'Mode révision',                   'Review mode indicator', 20),
('lesson.no_hearts_timer', 'lesson', 'Next life in',               'Prochaine vie dans',              'Countdown prefix for heart regen', 20),
('lesson.complete_score',  'lesson', 'Your score',                 'Ton score',                       'Score label on completion screen', 15),
('lesson.complete_xp',     'lesson', 'XP earned',                  'XP gagnés',                       'XP earned label on completion screen', 15),

-- ─── EXERCISES / MOLDS UI (10 strings) ────────────────────────────────────────
('exercise.check',         'lesson', 'Check',          'Vérifier',      'Check answer button', 12),
('exercise.hint',          'lesson', 'Hint',           'Indice',        'Show hint button', 10),
('exercise.self_correct',  'lesson', 'I got it',       'J''ai réussi',  'Flashcard self-correct button', 15),
('exercise.self_practice', 'lesson', 'I need more practice', 'J''ai besoin de pratiquer', 'Flashcard self-practice button', 25),
('exercise.transcript',    'lesson', 'Transcript',     'Transcription', 'Show transcript button', 15),
('exercise.true',          'lesson', 'True',           'Vrai',          'True/false option: true', 8),
('exercise.false',         'lesson', 'False',          'Faux',          'True/false option: false', 8),

-- ─── MOLD LABELS & PROMPTS (20 strings) ───────────────────────────────────────
('mold.flashcard_label',            'mold', 'Flashcard',               'Carte mémoire',                     'Mold type label shown in exercise header', 20),
('mold.fill_blank_label',           'mold', 'Fill in the blank',        'Compléter le texte',                'Mold type label', 25),
('mold.translate_label',            'mold', 'Translate',                'Traduire',                          'Mold type label', 15),
('mold.reorder_label',              'mold', 'Word order',               'Ordre des mots',                    'Mold type label', 20),
('mold.type_hear_label',            'mold', 'Type what you hear',       'Écrire ce qu''on entend',           'Mold type label', 25),
('mold.translate_input_placeholder','mold', 'Type your translation…',   'Tapez votre traduction…',           'Placeholder in TranslateSentence input', 30),
('mold.fill_blank_prompt',          'mold', 'Find the missing word',    'Trouve le mot manquant',            'Fill in blank instruction', NULL),
('mold.translate_prompt',           'mold', 'Translate this sentence',  'Traduis cette phrase',              'Translate instruction', NULL),
('mold.reorder_prompt',             'mold', 'Put the words in order',   'Remets les mots dans l''ordre',     'Word reorder instruction', NULL),
('mold.listen_prompt',              'mold', 'What did you hear?',       'Qu''as-tu entendu ?',               'Listen and choose instruction', NULL),
('mold.speak_prompt',               'mold', 'Say this word',            'Prononce ce mot',                   'Speak instruction', NULL),
('mold.match_prompt',               'mold', 'Match the pairs',          'Associe les paires',                'Match pairs instruction', NULL),
('mold.image_prompt',               'mold', 'Select the correct image', 'Sélectionne la bonne image',        'Image select instruction', NULL),
('mold.conversation_prompt',        'mold', 'Listen to the conversation','Écoute la conversation',           'Conversation listen instruction', NULL),
('mold.verb_prompt',                'mold', 'Choose the correct verb',  'Choisis le bon verbe',              'Select correct verb instruction', NULL),
('mold.flashcard_knew',             'mold', 'I knew it!',               'Je le savais !',                    'Flashcard positive self-assessment', 20),
('mold.flashcard_review',           'mold', 'Need review',              'À revoir',                          'Flashcard needs review self-assessment', 20),
('mold.flashcard_tap_to_flip',      'mold', 'Tap to flip',              'Appuie pour retourner',             'Flashcard hint text', 20),
('mold.replay_audio',               'mold', 'Replay',                   'Rejouer',                           'Replay audio button', 12),
('mold.hide_transcript',            'mold', 'Hide',                     'Masquer',                           'Hide transcript button', 10),

-- ─── GAMIFICATION (18 strings) ────────────────────────────────────────────────
('gamify.xp',                'gamification', 'XP',                           'XP',                            'XP label', 4),
('gamify.streak',            'gamification', 'Streak',                        'Série',                         'Streak label', 10),
('gamify.gems',              'gamification', 'Gems',                          'Gemmes',                        'Gems label', 10),
('gamify.leaderboard_weekly','gamification', 'Weekly leaderboard',            'Classement de la semaine',      'Leaderboard title', 25),
('gamify.achievements',      'gamification', 'Achievements',                  'Succès',                        'Achievements section label', 20),
('gamify.streak_lost',       'gamification', 'Your streak ended… Let''s start again today!', 'Ta série est terminée… Recommençons aujourd''hui !', 'Streak lost message', NULL),
('gamify.streak_celebration','gamification', 'Streak maintained! Keep it up!','Série maintenue ! Continue comme ça !', 'Streak maintained message', NULL),
('gamify.level_up',          'gamification', 'Level {{level}} reached!',      'Niveau {{level}} atteint !',    'Level up toast — {{level}} = number', 30),
('gamify.streak_a11y_label', 'gamification', 'Streak: {{count}} days',         'Série de {{count}} jours',      'Accessibility label for streak badge — {{count}} = days', 30),
('gamify.streak_title',      'gamification', 'Current streak',                'Série en cours',                'Streak title on screen', 20),
('gamify.streak_maintained', 'gamification', 'Day {{count}}! Keep it up! 🔥', 'Jour {{count}} ! Continue comme ça ! 🔥', 'Streak maintained toast — {{count}} = days', 35),
('gamify.streak_freeze_used','gamification', 'Streak freeze used! Your streak is saved!', 'Gel de série utilisé ! Ta série est sauvée !', 'Streak freeze toast', NULL),
('gamify.xp_earned',         'gamification', '+{{count}} XP',                 '+{{count}} XP',                 'XP earned notification — {{count}} = amount', 15),
('gamify.level_up_message',  'gamification', 'You''ve reached level {{level}}!','Tu es passé(e) au niveau {{level}} !', 'Level up full message — {{level}} = number', NULL),
('gamify.hearts_regen',      'gamification', 'Next life in {{time}}',          'Prochaine vie dans {{time}}',   'Heart regen countdown — {{time}} = timer', 30),
('gamify.leaderboard_resets','gamification', 'Resets in',                      'Réinitialisation dans',         'Leaderboard reset countdown prefix', 20),
('gamify.module_complete',   'gamification', 'Module complete! 🎉',            'Module terminé ! 🎉',           'Module completion toast', 25),
('gamify.perfect_lesson',    'gamification', 'Perfect lesson! ⭐',             'Leçon parfaite ! ⭐',           'Perfect lesson toast', 25),
('gamify.daily_goal_reached','gamification', 'Daily goal reached!',            'Objectif quotidien atteint !',  'Daily goal achieved toast', NULL),
('gamify.combo_bonus',       'gamification', 'Combo! +{{count}} XP bonus',    'Combo ! +{{count}} XP bonus',   'Combo XP bonus — {{count}} = amount', 30),

-- ─── SHOP (10 strings) ────────────────────────────────────────────────────────
('shop.title',              'shop', 'Shop',                    'Boutique',                'Shop screen title', 12),
('shop.refill_hearts',      'shop', 'Refill lives',            'Remplir les vies',        'Shop item title', 20),
('shop.refill_hearts_desc', 'shop', 'Restore your 5 lives',   'Restaure tes 5 vies',     'Shop item description', 25),
('shop.streak_freeze',      'shop', 'Streak freeze',          'Gel de série',            'Shop item title', 20),
('shop.streak_freeze_desc', 'shop', 'Protect 1 missed day',   'Protège 1 jour manqué',   'Shop item description', 25),
('shop.double_xp',          'shop', 'Double XP (1 hour)',     'Double XP (1 heure)',     'Shop item title', 25),
('shop.coming_soon',        'shop', 'Coming soon',            'Bientôt disponible',      'Unavailable item label', 20),
('shop.get_gems',           'shop', 'Get gems',               'Obtenir des gemmes',      'Get gems button', 20),
('shop.buy_button',         'shop', 'Buy — {{cost}} 💎',       'Acheter — {{cost}} 💎',   'Buy button — {{cost}} = gem price', 25),
('shop.not_enough_gems',    'shop', 'Not enough gems!',       'Pas assez de gemmes !',   'Insufficient gems error', NULL),
('shop.purchase_confirm',   'shop', 'Confirm purchase?',      'Confirmer l''achat ?',    'Purchase confirmation dialog', NULL),
('shop.gems_count',         'shop', 'Your gems',              'Tes gemmes',              'Gems balance label', 15),

-- ─── PROFILE (12 strings) ─────────────────────────────────────────────────────
('profile.settings',         'profile', 'Settings',            'Paramètres',            'Profile settings label', 15),
('profile.logout',           'profile', 'Log out',             'Déconnexion',           'Logout button', 15),
('profile.learning_since',   'profile', 'Learning since',      'Apprentissage depuis',  'Learning since label', 20),
('profile.daily_goal',       'profile', 'Daily goal',          'Objectif quotidien',    'Daily goal label', 20),
('profile.notifications',    'profile', 'Daily reminders',     'Rappels quotidiens',    'Notifications toggle label', 20),
('profile.title',            'profile', 'My profile',          'Mon profil',            'Profile screen title', 15),
('profile.total_xp',         'profile', 'Total XP',            'XP total',              'Total XP label', 12),
('profile.current_streak',   'profile', 'Current streak',      'Série actuelle',        'Current streak label', 20),
('profile.lessons_done',     'profile', 'Lessons completed',   'Leçons terminées',      'Lessons completed label', 25),
('profile.days_active',      'profile', 'Days active',         'Jours actifs',          'Days active label', 15),
('profile.daily_goal_minutes','profile','{{count}} minutes per day', '{{count}} minutes par jour', 'Daily goal setting — {{count}} = minutes', 30),
('profile.change_language',  'profile', 'Change language',     'Changer de langue',     'Change language button', 20),
('profile.edit_name',        'profile', 'Edit name',           'Modifier le nom',       'Edit name button', 15),
('profile.save',             'profile', 'Save',                'Sauvegarder',           'Save changes button', 12),

-- ─── ADMIN (14 strings) ───────────────────────────────────────────────────────
('admin.enter',             'admin', 'Enter admin mode',           'Entrer en mode admin',                  'Admin mode entry button', NULL),
('admin.bar',               'admin', '[ADMIN]',                    '[ADMIN]',                               'Admin mode banner label', 10),
('admin.validation_error',  'admin', 'Invalid content. Check required fields.', 'Contenu invalide. Vérifiez les champs obligatoires.', 'Admin validation error', NULL),
('admin.unsaved_changes',   'admin', 'Unsaved changes. Leave anyway?', 'Modifications non sauvegardées. Quitter quand même ?', 'Unsaved changes warning', NULL),
('admin.exercises_title',   'admin', 'Exercises',                  'Exercices',                             'Admin exercises screen title', 15),
('admin.refresh',           'admin', 'Refresh',                    'Actualiser',                            'Refresh button', 12),
('admin.modules_title',     'admin', 'Modules',                    'Modules',                               'Admin modules screen title', 12),
('admin.mode_label',        'admin', 'Admin Mode',                 'Mode Admin',                            'Admin mode toggle label', 15),
('admin.select_al',         'admin', 'App language',               'Langue de l''app',                      'App language selector label', 20),
('admin.select_ll',         'admin', 'Learning language',          'Langue d''apprentissage',               'Learning language selector label', 25),
('admin.save',              'admin', 'Save',                       'Sauvegarder',                           'Save button in admin', 12),
('admin.cancel',            'admin', 'Cancel',                     'Annuler',                               'Cancel button in admin', 12),
('admin.reorder_hint',      'admin', 'Hold to reorder',            'Maintiens pour réorganiser',            'Reorder hint in admin lists', NULL),
('admin.add_exercise',      'admin', 'Add exercise',               'Ajouter un exercice',                   'Add exercise button', 20),
('admin.delete_exercise',   'admin', 'Delete exercise',            'Supprimer l''exercice',                 'Delete exercise button', 20),
('admin.publish',           'admin', 'Publish',                    'Publier',                               'Publish button', 12),
('admin.unpublish',         'admin', 'Unpublish',                  'Dépublier',                             'Unpublish button', 12),

-- ─── CONFIRMATIONS (9 strings) ────────────────────────────────────────────────
('confirm.logout_title',        'confirm', 'Log out',                 'Déconnexion',                           'Logout confirmation dialog title', 15),
('confirm.logout_message',      'confirm', 'Are you sure you want to log out?', 'Es-tu sûr(e) de vouloir te déconnecter ?', 'Logout confirmation message', NULL),
('confirm.logout_confirm',      'confirm', 'Log out',                 'Se déconnecter',                        'Logout confirm button', 15),
('confirm.exit_lesson_title',   'confirm', 'Leave lesson?',           'Quitter la leçon ?',                    'Exit lesson dialog title', 20),
('confirm.exit_lesson_message', 'confirm', 'Are you sure you want to quit? Your progress for this lesson will be lost.', 'Tu veux vraiment quitter ? Ta progression pour cette leçon sera perdue.', 'Exit lesson dialog message', NULL),
('confirm.exit_continue',       'confirm', 'Continue lesson',         'Continuer la leçon',                    'Stay in lesson button', 20),
('confirm.exit_quit',           'confirm', 'Leave',                   'Quitter',                               'Leave lesson button', 10),
('confirm.unpublish_title',     'confirm', 'Unpublish this module?',  'Dépublier ce module ?',                 'Unpublish confirmation title', 30),
('confirm.unpublish_message',   'confirm', 'Students may be using this module. Confirm unpublishing?', 'Des élèves utilisent peut-être ce module. Confirmer la dépublication ?', 'Unpublish confirmation message', NULL),

-- ─── EMPTY STATES (8 strings) ─────────────────────────────────────────────────
('empty.achievements',      'empty_states', 'Your badges will appear here. Keep learning!', 'Tes badges apparaîtront ici. Continue à apprendre !', 'Empty achievements state', NULL),
('empty.adventure_start',   'empty_states', 'Your journey starts here! Tap the first module. 🌟', 'Ton voyage commence ici ! Appuie sur le premier module. 🌟', 'First visit to adventure path', NULL),
('empty.no_lessons',        'empty_states', 'No lessons available yet.',     'Aucune leçon disponible pour le moment.', 'Empty lesson list', NULL),
('empty.no_modules',        'empty_states', 'No modules available.',         'Aucun module disponible.',                'Empty module list', NULL),
('empty.browse_locked',     'empty_states', 'Continue your path to unlock more modules!', 'Continue ton parcours pour débloquer plus de modules !', 'Locked browse content', NULL),
('empty.search_no_results', 'empty_states', 'No results found.',             'Aucun résultat trouvé.',                  'Empty search results', NULL),
('empty.no_leaderboard',    'empty_states', 'Complete a lesson to join the leaderboard!', 'Complète une leçon pour rejoindre le classement !', 'Empty leaderboard', NULL),
('empty.no_progress',       'empty_states', 'No progress yet. Start your first lesson!', 'Pas encore de progression. Commence ta première leçon !', 'No progress yet', NULL),

-- ─── LEADERBOARD (2 strings) ──────────────────────────────────────────────────
('leaderboard.empty',  'gamification', 'Not enough participants this week yet.', 'Pas encore assez de participants cette semaine.', 'Empty leaderboard message', NULL),
('leaderboard.invite', 'gamification', 'Invite your friends to compare scores!', 'Invite tes amis pour comparer vos scores !',     'Invite friends to leaderboard', NULL),

-- ─── NOTIFICATIONS (2 strings) ────────────────────────────────────────────────
('notifications.streak_body',  'notifications', 'Don''t lose your {{streak}}-day streak! 🔥', 'Ne perdez pas votre série de {{streak}} jours ! 🔥', 'Push notification body — {{streak}} = days', NULL),
('notifications.practice_body','notifications', 'Time to practice! Your daily lesson is waiting.', 'Il est temps de pratiquer ! Votre leçon du jour vous attend.', 'Push notification body', NULL),

-- ─── FIRST-TIME HINTS (2 strings) ─────────────────────────────────────────────
('adventure.first_time', 'onboarding', 'Tap a module to start your first lesson! 🌟', 'Appuie sur un module pour commencer ta première leçon ! 🌟', 'First visit adventure tooltip', NULL),
('hearts.first_time',    'lesson',     'You have 5 lives. Each mistake costs one.',    'Tu as 5 vies. Chaque erreur en coûte une.',                 'First hearts explanation tooltip', NULL),

-- ─── OFFLINE / SYSTEM (2 strings) ─────────────────────────────────────────────
('offline.banner',   'errors', 'No internet connection', 'Pas de connexion internet', 'Offline banner', 30),
('browse.search',    'navigation', 'Search modules…',    'Rechercher des modules…',   'Browse search placeholder', 30)

ON CONFLICT (string_key) DO UPDATE SET
  en           = EXCLUDED.en,
  fr           = EXCLUDED.fr,
  context_note = EXCLUDED.context_note,
  max_chars    = EXCLUDED.max_chars,
  updated_at   = NOW();
