/**
 * French strings for first paint before DB fetch (auth + shell + lesson basics).
 * Merged over English fallback in loadAppStrings / t() so MVP AL=fr is readable offline.
 */
export const APP_STRINGS_FR_PRIORITY: Record<string, string> = {
  'auth.login_title': 'Connexion',
  'auth.register_title': 'Créer un compte',
  'auth.email': 'E-mail',
  'auth.password': 'Mot de passe',
  'auth.display_name': 'Nom affiché',
  'auth.sign_in': 'Se connecter',
  'auth.sign_up': "S'inscrire",
  'auth.no_account': 'Pas encore de compte ?',
  'auth.have_account': 'Déjà un compte ?',
  'auth.forgot_password': 'Mot de passe oublié ?',
  'auth.reset_sent': 'E-mail de réinitialisation envoyé.',
  'auth.confirm_email':
    'Un e-mail de confirmation a été envoyé. Vérifiez votre boîte puis connectez-vous.',
  'auth.error_invalid': 'E-mail ou mot de passe invalide.',
  'auth.error_generic': 'Une erreur est survenue. Réessayez.',

  'onboarding.select_ll_title': 'Quelle langue voulez-vous apprendre ?',
  'onboarding.select_ll_sub': 'Choisissez votre langue cible.',
  'onboarding.continue': 'Continuer',
  'onboarding.proficiency_title': 'Quel est votre niveau ?',
  'onboarding.proficiency_sub': 'Personnalisons votre parcours.',
  'onboarding.level_beginner_0': 'Débutant complet',
  'onboarding.level_beginner_0_desc': 'Je n’ai aucune base',
  'onboarding.level_beginner_1': 'Débutant',
  'onboarding.level_beginner_1_desc': 'Je connais quelques mots',
  'onboarding.level_intermediate': 'Intermédiaire',
  'onboarding.level_intermediate_desc': 'Je peux tenir une conversation simple',
  'onboarding.level_advanced': 'Avancé',
  'onboarding.level_advanced_desc': 'Je veux perfectionner mon niveau',

  'nav.home': 'Accueil',
  'nav.leaderboard': 'Classement',
  'nav.profile': 'Profil',
  'nav.browse': 'Parcourir',
  'browse.filter_all': 'Tous',
  'browse.filter_level': 'Nv {{n}}',
  'nav.shop': 'Boutique',
  'nav.admin': 'Admin',
  'nav.back': 'Retour',
  'nav.close': 'Fermer',

  'common.next': 'Suivant',
  'common.continue': 'Continuer',
  'common.skip': 'Passer',
  'common.try_again': 'Réessayer',
  'common.save': 'Enregistrer',
  'common.cancel': 'Annuler',
  'common.loading': 'Chargement…',
  'common.no_content': 'Aucun contenu pour le moment.',
  'common.close': 'Fermer',

  'btn.continue': 'Continuer',
  'btn.next': 'Suivant',
  'btn.back': 'Retour',
  'btn.cancel': 'Annuler',
  'btn.save': 'Enregistrer',
  'btn.retry': 'Réessayer',
  'btn.skip': 'Passer',
  'btn.confirm': 'Confirmer',
  'btn.done': 'Terminé',
  'btn.start': 'Commencer',
  'btn.yes': 'Oui',
  'btn.no': 'Non',

  'error.generic': 'Une erreur est survenue.',
  'error.network': 'Problème de connexion.',
  'error.network_retry': 'Réessayer',
  'error.login_failed': 'E-mail ou mot de passe incorrect.',
  'error.register_failed': 'Impossible de créer le compte.',

  'lesson.progress': 'Progression',
  'lesson.hearts': 'Vies',
  'lesson.correct': 'Correct !',
  'lesson.wrong': 'Pas tout à fait…',
  'lesson.complete_title': 'Leçon terminée !',
  'lesson.locked': 'Verrouillé',
  'lesson.start': 'Commencer',
  'exercise.check': 'Vérifier',
  'exercise.hint': 'Indice',

  'gamify.level': 'Niveau',
  'gamify.level_with_number': 'Niveau {{level}}',
};
