/**
 * Offline-safe fallback for app strings.
 * Used when AsyncStorage is empty AND the DB is unavailable.
 * Values are in English (the source language) — language-neutral offline safety net.
 * Keys mirror every row in migrations/021_app_strings_backfill.sql.
 */
export const APP_STRINGS_FALLBACK: Record<string, string> = {
  // Auth
  'auth.login_title': 'Log in',
  'auth.register_title': 'Create account',
  'auth.email': 'Email',
  'auth.password': 'Password',
  'auth.display_name': 'Display name',
  'auth.sign_in': 'Log in',
  'auth.sign_up': 'Sign up',
  'auth.no_account': 'No account yet?',
  'auth.have_account': 'Already have an account?',
  'auth.forgot_password': 'Forgot password?',
  'auth.reset_sent': 'Reset email sent.',
  'auth.confirm_email': 'A confirmation email has been sent. Check your inbox then log in.',
  'auth.error_invalid': 'Invalid email or password.',
  'auth.error_generic': 'Something went wrong. Please try again.',

  // Onboarding
  'onboarding.select_ll_title': 'What language do you want to learn?',
  'onboarding.select_ll_sub': 'Choose your target language.',
  'onboarding.continue': 'Continue',
  'onboarding.proficiency_title': 'What is your level?',
  'onboarding.proficiency_sub': 'Help us personalize your journey.',
  'onboarding.level_beginner_0': 'Complete beginner',
  'onboarding.level_beginner_0_desc': 'I have no prior knowledge',
  'onboarding.level_beginner_1': 'Beginner',
  'onboarding.level_beginner_1_desc': 'I know a few words',
  'onboarding.level_intermediate': 'Intermediate',
  'onboarding.level_intermediate_desc': 'I can hold a simple conversation',
  'onboarding.level_advanced': 'Advanced',
  'onboarding.level_advanced_desc': 'I want to perfect my level',

  // Navigation
  'nav.home': 'Home',
  'nav.leaderboard': 'Leaderboard',
  'nav.profile': 'Profile',
  'nav.browse': 'Browse',
  'nav.shop': 'Shop',
  'nav.admin': 'Admin',
  'nav.back': 'Back',
  'nav.close': 'Close',

  // Common actions
  'common.next': 'Next',
  'common.continue': 'Continue',
  'common.skip': 'Skip',
  'common.try_again': 'Try again',
  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.loading': 'Loading…',
  'common.no_content': 'No content available yet.',
  'common.close': 'Close',

  // Buttons
  'btn.continue': 'Continue',
  'btn.next': 'Next',
  'btn.back': 'Back',
  'btn.cancel': 'Cancel',
  'btn.save': 'Save',
  'btn.retry': 'Try again',
  'btn.skip': 'Skip',
  'btn.confirm': 'Confirm',
  'btn.done': 'Done',
  'btn.start': 'Start',
  'btn.yes': 'Yes',
  'btn.no': 'No',

  // Errors
  'error.generic': 'Something went wrong.',
  'error.network': 'Connection problem.',
  'error.network_retry': 'Try again',
  'error.empty': 'Nothing to display.',
  'error.login_failed': 'Incorrect email or password.',
  'error.register_failed': 'Could not create account.',
  'error.email_taken': 'This email is already in use.',
  'error.weak_password': 'Password must be at least 6 characters.',
  'error.load_lesson': 'Could not load the lesson.',
  'error.save_failed': 'Save failed. Try again.',
  'error.session_expired': 'Log in again to continue.',
  'error.image_fallback': 'Image unavailable',

  // Lesson
  'lesson.progress': 'Progress',
  'lesson.hearts': 'Lives',
  'lesson.correct': 'Correct!',
  'lesson.wrong': 'Not quite…',
  'lesson.almost': 'Almost! Check your spelling.',
  'lesson.complete_title': 'Lesson complete!',
  'lesson.complete_score': 'Your score',
  'lesson.complete_xp': 'XP earned',
  'lesson.no_hearts': 'No lives left. Come back later or buy lives.',
  'lesson.no_hearts_shop': 'Refill lives',
  'lesson.no_hearts_review': 'Review mode',
  'lesson.locked': 'Locked',
  'lesson.loading_patience': 'Loading your lesson…',
  'lesson.review_mode': 'Review mode',
  'lesson.no_hearts_timer': 'Next life in',
  'lesson.start': 'Start',

  // Exercises
  'exercise.check': 'Check',
  'exercise.hint': 'Hint',
  'exercise.self_correct': 'I got it',
  'exercise.self_practice': 'I need more practice',
  'exercise.transcript': 'Transcript',
  'exercise.true': 'True',
  'exercise.false': 'False',

  // Mold labels & prompts
  'mold.flashcard_label': 'Flashcard',
  'mold.fill_blank_label': 'Fill in the blank',
  'mold.translate_label': 'Translate',
  'mold.reorder_label': 'Word order',
  'mold.type_hear_label': 'Type what you hear',
  'mold.translate_input_placeholder': 'Type your translation…',
  'mold.fill_blank_prompt': 'Find the missing word',
  'mold.translate_prompt': 'Translate this sentence',
  'mold.reorder_prompt': 'Put the words in order',
  'mold.listen_prompt': 'What did you hear?',
  'mold.speak_prompt': 'Say this word',
  'mold.match_prompt': 'Match the pairs',
  'mold.image_prompt': 'Select the correct image',
  'mold.conversation_prompt': 'Listen to the conversation',
  'mold.verb_prompt': 'Choose the correct verb',
  'mold.flashcard_knew': 'I knew it!',
  'mold.flashcard_review': 'Need review',
  'mold.flashcard_tap_to_flip': 'Tap to flip',
  'mold.replay_audio': 'Replay',
  'mold.hide_transcript': 'Hide',

  // Gamification
  'gamify.xp': 'XP',
  'gamify.streak': 'Streak',
  'gamify.gems': 'Gems',
  'gamify.leaderboard_weekly': 'Weekly leaderboard',
  'gamify.achievements': 'Achievements',
  'gamify.streak_lost': "Your streak ended… Let's start again today!",
  'gamify.streak_celebration': 'Streak maintained! Keep it up!',
  'gamify.level_up': 'Level {{level}} reached!',
  'gamify.streak_a11y_label': 'Streak: {{count}} days',
  'gamify.streak_title': 'Current streak',
  'gamify.streak_maintained': 'Day {{count}}! Keep it up! 🔥',
  'gamify.streak_freeze_used': 'Streak freeze used! Your streak is saved!',
  'gamify.xp_earned': '+{{count}} XP',
  'gamify.level_up_message': "You've reached level {{level}}!",
  'gamify.hearts_regen': 'Next life in {{time}}',
  'gamify.leaderboard_resets': 'Resets in',
  'gamify.module_complete': 'Module complete! 🎉',
  'gamify.perfect_lesson': 'Perfect lesson! ⭐',
  'gamify.daily_goal_reached': 'Daily goal reached!',
  'gamify.combo_bonus': 'Combo! +{{count}} XP bonus',

  // Shop
  'shop.title': 'Shop',
  'shop.refill_hearts': 'Refill lives',
  'shop.refill_hearts_desc': 'Restore your 5 lives',
  'shop.streak_freeze': 'Streak freeze',
  'shop.streak_freeze_desc': 'Protect 1 missed day',
  'shop.double_xp': 'Double XP (1 hour)',
  'shop.coming_soon': 'Coming soon',
  'shop.get_gems': 'Get gems',
  'shop.buy_button': 'Buy — {{cost}} 💎',
  'shop.not_enough_gems': 'Not enough gems!',
  'shop.purchase_confirm': 'Confirm purchase?',
  'shop.gems_count': 'Your gems',

  // Profile
  'profile.settings': 'Settings',
  'profile.logout': 'Log out',
  'profile.learning_since': 'Learning since',
  'profile.daily_goal': 'Daily goal',
  'profile.notifications': 'Daily reminders',
  'profile.title': 'My profile',
  'profile.total_xp': 'Total XP',
  'profile.current_streak': 'Current streak',
  'profile.lessons_done': 'Lessons completed',
  'profile.days_active': 'Days active',
  'profile.daily_goal_minutes': '{{count}} minutes per day',
  'profile.change_language': 'Change language',
  'profile.edit_name': 'Edit name',
  'profile.save': 'Save',

  // Admin
  'admin.enter': 'Enter admin mode',
  'admin.bar': '[ADMIN]',
  'admin.validation_error': 'Invalid content. Check required fields.',
  'admin.unsaved_changes': 'Unsaved changes. Leave anyway?',
  'admin.exercises_title': 'Exercises',
  'admin.refresh': 'Refresh',
  'admin.modules_title': 'Modules',
  'admin.mode_label': 'Admin Mode',
  'admin.select_al': 'App language',
  'admin.select_ll': 'Learning language',
  'admin.save': 'Save',
  'admin.cancel': 'Cancel',
  'admin.reorder_hint': 'Hold to reorder',
  'admin.add_exercise': 'Add exercise',
  'admin.delete_exercise': 'Delete exercise',
  'admin.publish': 'Publish',
  'admin.unpublish': 'Unpublish',

  // Confirmations
  'confirm.logout_title': 'Log out',
  'confirm.logout_message': 'Are you sure you want to log out?',
  'confirm.logout_confirm': 'Log out',
  'confirm.exit_lesson_title': 'Leave lesson?',
  'confirm.exit_lesson_message': 'Are you sure you want to quit? Your progress for this lesson will be lost.',
  'confirm.exit_continue': 'Continue lesson',
  'confirm.exit_quit': 'Leave',
  'confirm.unpublish_title': 'Unpublish this module?',
  'confirm.unpublish_message': 'Students may be using this module. Confirm unpublishing?',

  // Empty states
  'empty.achievements': 'Your badges will appear here. Keep learning!',
  'empty.adventure_start': 'Your journey starts here! Tap the first module. 🌟',
  'empty.no_lessons': 'No lessons available yet.',
  'empty.no_modules': 'No modules available.',
  'empty.browse_locked': 'Continue your path to unlock more modules!',
  'empty.search_no_results': 'No results found.',
  'empty.no_leaderboard': 'Complete a lesson to join the leaderboard!',
  'empty.no_progress': 'No progress yet. Start your first lesson!',

  // Leaderboard
  'leaderboard.empty': 'Not enough participants this week yet.',
  'leaderboard.invite': 'Invite your friends to compare scores!',

  // Notifications
  'notifications.streak_body': "Don't lose your {{streak}}-day streak! 🔥",
  'notifications.practice_body': 'Time to practice! Your daily lesson is waiting.',

  // First-time hints
  'adventure.first_time': 'Tap a module to start your first lesson! 🌟',
  'hearts.first_time': 'You have 5 lives. Each mistake costs one.',

  // Offline / system
  'offline.banner': 'No internet connection',
  'offline.progress_saved': "You're offline. Progress saved — it'll sync when you're back.",
  'offline.syncing': 'Syncing…',
  'offline.synced': 'All synced!',
  'browse.search': 'Search modules…',

  // UX Feedback Layer — Phase 1: Core Lesson Feedback
  'lesson.wrong_detail_format': 'The correct answer is "{{answer}}".',
  'lesson.wrong_fallback': 'The correct answer is "{{answer}}".',
  'lesson.almost_enhanced': 'So close!',
  'lesson.retry_success': 'You got it this time!',
  'lesson.requeue_intro': "Let's try that one again!",
  'lesson.tricky_word': "This one's tricky! Here's an extra clue.",
  'exercise.i_dont_know': "I don't know",
  'exercise.skip_reveal': "No worries! The answer is \"{{answer}}\".",
  'exercise.skip_requeue': "You'll see this one again soon.",
  'exercise.skip_cost': 'Skipping costs 1 life',
  'exercise.hint_clue': "Here's a clue…",
  'lesson.correct_1': 'Correct!',
  'lesson.correct_2': 'Nice!',
  'lesson.correct_3': 'Great job!',
  'lesson.correct_4': 'Nailed it!',
  'lesson.correct_5': 'You got it!',
  'lesson.correct_6': 'Well done!',
  'lesson.correct_7': "That's right!",
  'lesson.correct_8': 'Excellent!',
  'lesson.correct_combo_1': 'On fire! 🔥',
  'lesson.correct_combo_2': 'Keep it going!',
  'lesson.correct_combo_3': 'Unstoppable!',
  'lesson.correct_combo_4': "You're on a roll!",
  'lesson.correct_recovery_1': 'You got it this time!',
  'lesson.correct_recovery_2': "That's the one!",
  'lesson.correct_recovery_3': 'See? You know this!',
  'lesson.correct_recovery_4': 'Bounced back!',

  // UX Feedback Layer — Phase 1: Combo
  'gamify.combo_3': '3 in a row!',
  'gamify.combo_5': 'On fire!',
  'gamify.combo_10': 'Unstoppable!',

  // UX Feedback Layer — Phase 2: Progress & Success
  'lesson.complete_words_learned': 'New words',
  'lesson.complete_review': 'Review these',
  'lesson.complete_next': 'Next: {{title}}',
  'lesson.complete_share': 'Share your progress',
  'gamify.module_next': 'Up next: {{name}}',
  'gamify.module_continue': 'Continue journey',
  'gamify.level_descriptor_beginner': "Beginner — You're just getting started!",
  'gamify.level_descriptor_intermediate': 'Intermediate — You can hold a basic conversation!',
  'gamify.level_descriptor_advanced': "Advanced — You're gaining real fluency!",
  'gamify.level_descriptor_expert': "Expert — You're mastering {{language}}!",
  'profile.progress_title': 'Your progress',
  'profile.weak_spots': 'Words to practice',
  'profile.practice': 'Practice',
  'profile.no_weak_spots': 'No tricky words yet. Keep learning!',

  // UX Feedback Layer — Phase 3: Onboarding & Retention
  'onboarding.motivation_title': 'What\'s your motivation?',
  'onboarding.motivation_sub': 'This helps us personalize your journey.',
  'onboarding.goal_title': 'How much time can you commit each day?',
  'onboarding.goal_casual': '5 minutes',
  'onboarding.goal_regular': '10 minutes',
  'onboarding.goal_serious': '15 minutes',
  'onboarding.goal_intense': '20 minutes',
  'onboarding.notifications_title': 'Can we send you a daily reminder?',
  'onboarding.notifications_sub': 'People who enable reminders are 3x more likely to reach their goal.',
  'onboarding.notifications_enable': 'Enable reminders',
  'onboarding.notifications_skip': 'Not now',
  'onboarding.welcome_back_cta': 'Continue learning',
  'onboarding.day2': 'Welcome back! Day 2 — your streak is alive! 🔥',
  'onboarding.day3': "3 days in a row! You're building a real habit. 🌱",
  'onboarding.day5': 'Halfway to your first weekly streak! 5 days strong.',
  'onboarding.welcome_back_sub': 'Yesterday you learned {{count}} words. Ready for more?',
  'gamify.bonus_round': 'One more lesson? Earn bonus XP!',

  // UX Feedback Layer — Phase 4: Edge Cases
  'lesson.recharge_title': 'Recharge time!',
  'lesson.recharge_subtitle': 'Your lives are regenerating. Practice while you wait!',
  'lesson.practice_mode': 'Practice mode',
  'lesson.practice_banner': 'Practice mode — no lives needed',
  'lesson.challenge_offer': 'Want a challenge? Try a harder exercise!',
  'lesson.break_suggestion': "You've been amazing! Studies show breaks improve retention. See you tomorrow! 🧠",
  'error.lesson_offline': "Can't load lesson. Check your connection and try again.",
};
