/** Fallback French UI strings when DB ui_strings unavailable */
export const FRENCH_UI_FALLBACK: Record<string, string> = {
  'auth.login_title': 'Connexion',
  'auth.register_title': 'Créer un compte',
  'auth.email': 'E-mail',
  'auth.password': 'Mot de passe',
  'auth.display_name': 'Nom affiché',
  'auth.sign_in': 'Se connecter',
  'auth.sign_up': "S'inscrire",
  'auth.no_account': 'Pas encore de compte ?',
  'auth.have_account': 'Déjà un compte ?',
  'auth.forgot_password': 'Mot de passe oublié ?',
  'auth.reset_sent': 'E-mail de réinitialisation envoyé.',
  'auth.error_invalid': 'E-mail ou mot de passe invalide.',
  'auth.error_generic': 'Une erreur est survenue. Réessayez.',
  'onboarding.select_ll_title': 'Quelle langue voulez-vous apprendre ?',
  'onboarding.select_ll_sub': 'Choisissez votre langue cible.',
  'onboarding.continue': 'Continuer',
  'onboarding.proficiency_title': 'Quel est votre niveau ?',
  'onboarding.proficiency_sub': 'Aidez-nous à personnaliser votre parcours.',
  'onboarding.level_beginner_0': 'Débutant complet',
  'onboarding.level_beginner_0_desc': "Je n'ai aucune connaissance",
  'onboarding.level_beginner_1': 'Débutant',
  'onboarding.level_beginner_1_desc': 'Je connais quelques mots',
  'onboarding.level_intermediate': 'Intermédiaire',
  'onboarding.level_intermediate_desc': 'Je peux tenir une conversation simple',
  'onboarding.level_advanced': 'Avancé',
  'onboarding.level_advanced_desc': 'Je veux perfectionner mon niveau',
  'nav.home': 'Accueil',
  'nav.leaderboard': 'Classement',
  'nav.profile': 'Profil',
  'nav.browse': 'Parcourir',
  'nav.shop': 'Boutique',
  'common.next': 'Suivant',
  'common.continue': 'Continuer',
  'common.skip': 'Passer',
  'common.try_again': 'Réessayer',
  'common.save': 'Enregistrer',
  'common.cancel': 'Annuler',
  'common.loading': 'Chargement…',
  'common.close': 'Fermer',
  'error.network': 'Problème de connexion.',
  'error.empty': 'Aucun élément à afficher.',
  'lesson.progress': 'Progression',
  'lesson.hearts': 'Vies',
  'lesson.correct': 'Correct !',
  'lesson.wrong': 'Pas tout à fait…',
  'lesson.complete_title': 'Leçon terminée !',
  'lesson.no_hearts': "Plus de vies. Revenez plus tard ou achetez des vies.",
  'exercise.check': 'Vérifier',
  'exercise.hint': 'Indice',
  'exercise.self_correct': "J'ai réussi",
  'exercise.self_practice': "J'ai besoin de pratiquer",
  'exercise.transcript': 'Transcription',
  'exercise.true': 'Vrai',
  'exercise.false': 'Faux',
  'gamify.xp': 'XP',
  'gamify.streak': 'Série',
  'gamify.gems': 'Gemmes',
  'gamify.leaderboard_weekly': 'Classement de la semaine',
  'gamify.achievements': 'Succès',
  'shop.title': 'Boutique',
  'shop.refill_hearts': 'Remplir les vies',
  'shop.streak_freeze': 'Gel de série',
  'shop.coming_soon': 'Bientôt disponible',
  'profile.settings': 'Paramètres',
  'profile.logout': 'Déconnexion',
  'profile.learning_since': 'Apprentissage depuis',
  'profile.daily_goal': 'Objectif quotidien',
  'profile.notifications': 'Rappels quotidiens',
  'admin.enter': 'Entrer en mode admin',
  'admin.bar': '[ADMIN]',
  'browse.search': 'Rechercher des modules…',
  'lesson.locked': 'Verrouillé',
  'notifications.streak_body': 'Ne perdez pas votre série de {streak} jours ! 🔥',
  'notifications.practice_body': 'Il est temps de pratiquer ! Votre leçon du jour vous attend.',
};
