UPDATE modules SET
  slug              = 'decrire_personnes',
  title_al          = 'Décrire les personnes',
  title_ll          = 'Describing People',
  description_al    = 'Apprenez à décrire les personnes : leur apparence physique et leur personnalité.',
  icon_name         = 'person',
  color_hex         = '#3498DB',
  difficulty_level  = 2,
  is_published      = true,
  xp_reward         = 100,
  estimated_minutes = 15
WHERE slug = 'shell_module_17';

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'decrire_personnes'), 'decrire_personnes_lesson_1', 'L''apparence physique', 1, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'decrire_personnes_lesson_1'), 'flashcard', '{"front": "tall", "back": "grand / grande"}'::jsonb, 1, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'decrire_personnes_lesson_1'), 'flashcard', '{"front": "short", "back": "petit / petite"}'::jsonb, 2, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'decrire_personnes_lesson_1'), 'translate_sentence', '{"prompt": "Il a les cheveux bruns et les yeux bleus.", "answer": "He has brown hair and blue eyes.", "hint": "cheveux = hair, yeux = eyes"}'::jsonb, 3, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'decrire_personnes_lesson_1'), 'fill_in_the_blank', '{"sentence": "She has ___ hair.", "answer": "long", "options": ["long", "fast", "loud", "cold"]}'::jsonb, 4, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'decrire_personnes_lesson_1'), 'word_reorder', '{"words": ["She", "is", "very", "tall"], "answer": "She is very tall"}'::jsonb, 5, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'decrire_personnes_lesson_1'), 'true_or_false', '{"statement": "Grand means short in French.", "answer": false, "explanation": "Grand means tall; petit means short"}'::jsonb, 6, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'decrire_personnes_lesson_1'), 'listen_and_choose', '{"audio_text": "blue eyes", "options": ["green eyes", "blue eyes", "brown eyes", "grey eyes"], "answer": "blue eyes"}'::jsonb, 7, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'decrire_personnes_lesson_1'), 'select_correct_verb', '{"sentence": "She ___ tall with blonde hair.", "answer": "is", "options": ["is", "are", "have", "were"]}'::jsonb, 8, 1, 10, true);

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'decrire_personnes'), 'decrire_personnes_lesson_2', 'La personnalité', 2, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'decrire_personnes_lesson_2'), 'flashcard', '{"front": "friendly", "back": "sympa / aimable"}'::jsonb, 1, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'decrire_personnes_lesson_2'), 'flashcard', '{"front": "serious", "back": "sérieux / sérieuse"}'::jsonb, 2, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'decrire_personnes_lesson_2'), 'translate_sentence', '{"prompt": "Mon collègue est très sérieux et travailleur.", "answer": "My colleague is very serious and hardworking.", "hint": "travailleur = hardworking"}'::jsonb, 3, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'decrire_personnes_lesson_2'), 'fill_in_the_blank', '{"sentence": "My teacher is very ___ and patient.", "answer": "kind", "options": ["kind", "table", "blue", "fast"]}'::jsonb, 4, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'decrire_personnes_lesson_2'), 'word_reorder', '{"words": ["He", "is", "calm", "and", "patient"], "answer": "He is calm and patient"}'::jsonb, 5, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'decrire_personnes_lesson_2'), 'true_or_false', '{"statement": "Timide means outgoing in English.", "answer": false, "explanation": "Timide means shy, not outgoing"}'::jsonb, 6, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'decrire_personnes_lesson_2'), 'listen_and_choose', '{"audio_text": "outgoing", "options": ["shy", "outgoing", "serious", "lazy"], "answer": "outgoing"}'::jsonb, 7, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'decrire_personnes_lesson_2'), 'type_what_you_hear', '{"audio_text": "friendly", "answer": "friendly", "hint": "a pleasant personality trait"}'::jsonb, 8, 1, 10, true);

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'decrire_personnes'), 'decrire_personnes_lesson_3', 'Décrire ses collègues', 3, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'decrire_personnes_lesson_3'), 'flashcard', '{"front": "colleague", "back": "collègue"}'::jsonb, 1, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'decrire_personnes_lesson_3'), 'flashcard', '{"front": "classmate", "back": "camarade de classe"}'::jsonb, 2, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'decrire_personnes_lesson_3'), 'translate_sentence', '{"prompt": "Ma camarade a les yeux verts et les cheveux courts.", "answer": "My classmate has green eyes and short hair.", "hint": "cheveux courts = short hair"}'::jsonb, 3, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'decrire_personnes_lesson_3'), 'fill_in_the_blank', '{"sentence": "My ___ is very tall and has brown eyes.", "answer": "colleague", "options": ["colleague", "kitchen", "window", "pencil"]}'::jsonb, 4, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'decrire_personnes_lesson_3'), 'word_reorder', '{"words": ["My", "colleague", "is", "smart", "and", "funny"], "answer": "My colleague is smart and funny"}'::jsonb, 5, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'decrire_personnes_lesson_3'), 'true_or_false', '{"statement": "Petit describes someone who is tall.", "answer": false, "explanation": "Petit means small or short, not tall"}'::jsonb, 6, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'decrire_personnes_lesson_3'), 'listen_and_choose', '{"audio_text": "short hair", "options": ["long hair", "short hair", "curly hair", "straight hair"], "answer": "short hair"}'::jsonb, 7, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'decrire_personnes_lesson_3'), 'select_correct_verb', '{"sentence": "She ___ glasses and curly hair.", "answer": "has", "options": ["has", "have", "is", "are"]}'::jsonb, 8, 1, 10, true);

UPDATE modules SET
  slug              = 'emotions_sentiments',
  title_al          = 'Les émotions et les sentiments',
  title_ll          = 'Emotions & Feelings',
  description_al    = 'Exprimez vos émotions et sentiments en anglais dans des contextes professionnels.',
  icon_name         = 'heart',
  color_hex         = '#E74C3C',
  difficulty_level  = 2,
  is_published      = true,
  xp_reward         = 100,
  estimated_minutes = 15
WHERE slug = 'shell_module_18';

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'emotions_sentiments'), 'emotions_sentiments_lesson_1', 'Les émotions positives', 1, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'emotions_sentiments_lesson_1'), 'flashcard', '{"front": "happy", "back": "heureux / heureuse"}'::jsonb, 1, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'emotions_sentiments_lesson_1'), 'flashcard', '{"front": "proud", "back": "fier / fière"}'::jsonb, 2, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'emotions_sentiments_lesson_1'), 'translate_sentence', '{"prompt": "Je suis très content de mon résultat.", "answer": "I am very pleased with my result.", "hint": "content = pleased, résultat = result"}'::jsonb, 3, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'emotions_sentiments_lesson_1'), 'fill_in_the_blank', '{"sentence": "I am ___ to start my new job.", "answer": "excited", "options": ["excited", "worried", "tired", "bored"]}'::jsonb, 4, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'emotions_sentiments_lesson_1'), 'word_reorder', '{"words": ["I", "feel", "happy", "and", "proud", "today"], "answer": "I feel happy and proud today"}'::jsonb, 5, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'emotions_sentiments_lesson_1'), 'true_or_false', '{"statement": "Fier means sad in English.", "answer": false, "explanation": "Fier means proud, not sad"}'::jsonb, 6, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'emotions_sentiments_lesson_1'), 'listen_and_choose', '{"audio_text": "excited", "options": ["bored", "nervous", "excited", "sad"], "answer": "excited"}'::jsonb, 7, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'emotions_sentiments_lesson_1'), 'select_correct_verb', '{"sentence": "She ___ very proud of her work.", "answer": "feels", "options": ["feels", "feel", "felt", "feeling"]}'::jsonb, 8, 1, 10, true);

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'emotions_sentiments'), 'emotions_sentiments_lesson_2', 'Les émotions négatives', 2, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'emotions_sentiments_lesson_2'), 'flashcard', '{"front": "sad", "back": "triste"}'::jsonb, 1, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'emotions_sentiments_lesson_2'), 'flashcard', '{"front": "stressed", "back": "stressé / stressée"}'::jsonb, 2, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'emotions_sentiments_lesson_2'), 'translate_sentence', '{"prompt": "Je me sens nerveux avant la réunion.", "answer": "I feel nervous before the meeting.", "hint": "nerveux = nervous, réunion = meeting"}'::jsonb, 3, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'emotions_sentiments_lesson_2'), 'fill_in_the_blank', '{"sentence": "I feel ___ when I have too much work.", "answer": "stressed", "options": ["stressed", "happy", "excited", "calm"]}'::jsonb, 4, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'emotions_sentiments_lesson_2'), 'word_reorder', '{"words": ["She", "feels", "sad", "and", "disappointed"], "answer": "She feels sad and disappointed"}'::jsonb, 5, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'emotions_sentiments_lesson_2'), 'true_or_false', '{"statement": "Déçu means nervous in English.", "answer": false, "explanation": "Déçu means disappointed, not nervous"}'::jsonb, 6, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'emotions_sentiments_lesson_2'), 'listen_and_choose', '{"audio_text": "nervous", "options": ["angry", "nervous", "calm", "happy"], "answer": "nervous"}'::jsonb, 7, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'emotions_sentiments_lesson_2'), 'type_what_you_hear', '{"audio_text": "disappointed", "answer": "disappointed", "hint": "when things do not go as expected"}'::jsonb, 8, 1, 10, true);

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'emotions_sentiments'), 'emotions_sentiments_lesson_3', 'Exprimer ses sentiments au travail', 3, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'emotions_sentiments_lesson_3'), 'flashcard', '{"front": "overwhelmed", "back": "débordé / débordée"}'::jsonb, 1, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'emotions_sentiments_lesson_3'), 'flashcard', '{"front": "motivated", "back": "motivé / motivée"}'::jsonb, 2, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'emotions_sentiments_lesson_3'), 'translate_sentence', '{"prompt": "Je suis stressé parce que le délai est demain.", "answer": "I am stressed because the deadline is tomorrow.", "hint": "délai = deadline, demain = tomorrow"}'::jsonb, 3, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'emotions_sentiments_lesson_3'), 'fill_in_the_blank', '{"sentence": "I feel ___ when my team supports me.", "answer": "motivated", "options": ["motivated", "bored", "angry", "confused"]}'::jsonb, 4, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'emotions_sentiments_lesson_3'), 'word_reorder', '{"words": ["I", "am", "overwhelmed", "with", "work", "this", "week"], "answer": "I am overwhelmed with work this week"}'::jsonb, 5, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'emotions_sentiments_lesson_3'), 'true_or_false', '{"statement": "Je me sens bien and I feel good express the same positive state.", "answer": true, "explanation": "Both phrases convey feeling well or in a good state"}'::jsonb, 6, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'emotions_sentiments_lesson_3'), 'listen_and_choose', '{"audio_text": "I feel overwhelmed", "options": ["I feel bored", "I feel overwhelmed", "I feel excited", "I feel relaxed"], "answer": "I feel overwhelmed"}'::jsonb, 7, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'emotions_sentiments_lesson_3'), 'select_correct_verb', '{"sentence": "He ___ angry when people interrupt him.", "answer": "gets", "options": ["gets", "get", "got", "getting"]}'::jsonb, 8, 1, 10, true);

UPDATE modules SET
  slug              = 'technologie_communication',
  title_al          = 'La technologie et la communication',
  title_ll          = 'Technology & Communication',
  description_al    = 'Maîtrisez le vocabulaire de la technologie et de la communication numérique.',
  icon_name         = 'laptop',
  color_hex         = '#2ECC71',
  difficulty_level  = 2,
  is_published      = true,
  xp_reward         = 100,
  estimated_minutes = 15
WHERE slug = 'shell_module_19';

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'technologie_communication'), 'technologie_communication_lesson_1', 'Les appareils numériques', 1, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'technologie_communication_lesson_1'), 'flashcard', '{"front": "smartphone", "back": "téléphone portable / smartphone"}'::jsonb, 1, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'technologie_communication_lesson_1'), 'flashcard', '{"front": "password", "back": "mot de passe"}'::jsonb, 2, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'technologie_communication_lesson_1'), 'translate_sentence', '{"prompt": "Mon ordinateur portable est lent aujourd''hui.", "answer": "My laptop is slow today.", "hint": "ordinateur portable = laptop, lent = slow"}'::jsonb, 3, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'technologie_communication_lesson_1'), 'fill_in_the_blank', '{"sentence": "I need to charge my ___.", "answer": "phone", "options": ["phone", "desk", "chair", "book"]}'::jsonb, 4, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'technologie_communication_lesson_1'), 'word_reorder', '{"words": ["I", "forgot", "my", "password", "again"], "answer": "I forgot my password again"}'::jsonb, 5, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'technologie_communication_lesson_1'), 'true_or_false', '{"statement": "Application in French refers to a software app.", "answer": true, "explanation": "Application or appli in French means app"}'::jsonb, 6, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'technologie_communication_lesson_1'), 'listen_and_choose', '{"audio_text": "video call", "options": ["phone call", "text message", "video call", "email"], "answer": "video call"}'::jsonb, 7, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'technologie_communication_lesson_1'), 'select_correct_verb', '{"sentence": "She ___ a video call every Monday.", "answer": "has", "options": ["has", "have", "do", "does"]}'::jsonb, 8, 1, 10, true);

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'technologie_communication'), 'technologie_communication_lesson_2', 'Appels et e-mails', 2, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'technologie_communication_lesson_2'), 'flashcard', '{"front": "to call", "back": "appeler"}'::jsonb, 1, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'technologie_communication_lesson_2'), 'flashcard', '{"front": "attachment", "back": "pièce jointe"}'::jsonb, 2, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'technologie_communication_lesson_2'), 'translate_sentence', '{"prompt": "Pouvez-vous m''envoyer le fichier par e-mail ?", "answer": "Can you send me the file by email?", "hint": "fichier = file"}'::jsonb, 3, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'technologie_communication_lesson_2'), 'fill_in_the_blank', '{"sentence": "Please ___ me the report by end of day.", "answer": "send", "options": ["send", "eat", "build", "open"]}'::jsonb, 4, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'technologie_communication_lesson_2'), 'word_reorder', '{"words": ["I", "will", "call", "you", "tomorrow", "morning"], "answer": "I will call you tomorrow morning"}'::jsonb, 5, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'technologie_communication_lesson_2'), 'true_or_false', '{"statement": "You start a professional email with Hey!", "answer": false, "explanation": "Professional emails start with Dear or Hello, not Hey"}'::jsonb, 6, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'technologie_communication_lesson_2'), 'listen_and_choose', '{"audio_text": "Can you send me the file?", "options": ["Can you call me?", "Can you send me the file?", "Can you delete the file?", "Can you open the file?"], "answer": "Can you send me the file?"}'::jsonb, 7, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'technologie_communication_lesson_2'), 'type_what_you_hear', '{"audio_text": "attachment", "answer": "attachment", "hint": "a file added to an email"}'::jsonb, 8, 1, 10, true);

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'technologie_communication'), 'technologie_communication_lesson_3', 'Partager des fichiers', 3, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'technologie_communication_lesson_3'), 'flashcard', '{"front": "to download", "back": "télécharger"}'::jsonb, 1, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'technologie_communication_lesson_3'), 'flashcard', '{"front": "link", "back": "lien"}'::jsonb, 2, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'technologie_communication_lesson_3'), 'translate_sentence', '{"prompt": "Je vais partager le lien avec toute l''équipe.", "answer": "I will share the link with the whole team.", "hint": "partager = share, équipe = team"}'::jsonb, 3, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'technologie_communication_lesson_3'), 'fill_in_the_blank', '{"sentence": "I need to ___ the document before the meeting.", "answer": "upload", "options": ["upload", "delete", "ignore", "forget"]}'::jsonb, 4, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'technologie_communication_lesson_3'), 'word_reorder', '{"words": ["Can", "you", "share", "your", "screen", "please"], "answer": "Can you share your screen please"}'::jsonb, 5, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'technologie_communication_lesson_3'), 'true_or_false', '{"statement": "Télécharger can mean both upload and download in French.", "answer": true, "explanation": "Context determines direction; télécharger covers both in common usage"}'::jsonb, 6, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'technologie_communication_lesson_3'), 'listen_and_choose', '{"audio_text": "share your screen", "options": ["check your email", "share your screen", "delete the file", "open the app"], "answer": "share your screen"}'::jsonb, 7, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'technologie_communication_lesson_3'), 'select_correct_verb', '{"sentence": "He ___ the file to the cloud every day.", "answer": "uploads", "options": ["uploads", "upload", "downloaded", "deleting"]}'::jsonb, 8, 1, 10, true);
