UPDATE modules SET
  slug              = 'les_professions',
  title_al          = 'Les professions',
  title_ll          = 'Jobs & Professions',
  description_al    = 'Découvrez les noms des métiers et apprenez à décrire votre travail en anglais.',
  icon_name         = 'briefcase',
  color_hex         = '#9B59B6',
  difficulty_level  = 2,
  is_published      = true,
  xp_reward         = 100,
  estimated_minutes = 15
WHERE slug = 'shell_module_20';

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'les_professions'), 'les_professions_lesson_1', 'Les métiers', 1, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'les_professions_lesson_1'), 'flashcard', '{"front": "nurse", "back": "infirmier / infirmière"}'::jsonb, 1, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'les_professions_lesson_1'), 'flashcard', '{"front": "engineer", "back": "ingénieur / ingénieure"}'::jsonb, 2, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'les_professions_lesson_1'), 'translate_sentence', '{"prompt": "Mon père est chauffeur et ma mère est professeure.", "answer": "My father is a driver and my mother is a teacher.", "hint": "chauffeur = driver, professeure = teacher"}'::jsonb, 3, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'les_professions_lesson_1'), 'fill_in_the_blank', '{"sentence": "The ___ cooked an amazing meal.", "answer": "chef", "options": ["chef", "pilot", "nurse", "lawyer"]}'::jsonb, 4, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'les_professions_lesson_1'), 'word_reorder', '{"words": ["She", "is", "a", "software", "engineer"], "answer": "She is a software engineer"}'::jsonb, 5, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'les_professions_lesson_1'), 'true_or_false', '{"statement": "An infirmier is a doctor.", "answer": false, "explanation": "An infirmier is a nurse; a doctor is médecin"}'::jsonb, 6, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'les_professions_lesson_1'), 'listen_and_choose', '{"audio_text": "teacher", "options": ["nurse", "teacher", "engineer", "driver"], "answer": "teacher"}'::jsonb, 7, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'les_professions_lesson_1'), 'select_correct_verb', '{"sentence": "He ___ as a chef at a restaurant.", "answer": "works", "options": ["works", "work", "working", "worked"]}'::jsonb, 8, 1, 10, true);

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'les_professions'), 'les_professions_lesson_2', 'Décrire son travail', 2, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'les_professions_lesson_2'), 'flashcard', '{"front": "duties", "back": "responsabilités"}'::jsonb, 1, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'les_professions_lesson_2'), 'flashcard', '{"front": "salary", "back": "salaire"}'::jsonb, 2, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'les_professions_lesson_2'), 'translate_sentence', '{"prompt": "Mes responsabilités incluent la gestion des clients.", "answer": "My duties include managing clients.", "hint": "gestion = management"}'::jsonb, 3, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'les_professions_lesson_2'), 'fill_in_the_blank', '{"sentence": "I ___ patients at the hospital every day.", "answer": "help", "options": ["help", "avoid", "ignore", "sell"]}'::jsonb, 4, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'les_professions_lesson_2'), 'word_reorder', '{"words": ["I", "manage", "a", "team", "of", "five", "people"], "answer": "I manage a team of five people"}'::jsonb, 5, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'les_professions_lesson_2'), 'true_or_false', '{"statement": "A comptable works with money and accounts.", "answer": true, "explanation": "A comptable is an accountant who manages finances"}'::jsonb, 6, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'les_professions_lesson_2'), 'listen_and_choose', '{"audio_text": "I work full time", "options": ["I work part time", "I work full time", "I work from home", "I work overnight"], "answer": "I work full time"}'::jsonb, 7, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'les_professions_lesson_2'), 'type_what_you_hear', '{"audio_text": "responsibilities", "answer": "responsibilities", "hint": "your job duties"}'::jsonb, 8, 1, 10, true);

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'les_professions'), 'les_professions_lesson_3', 'Chercher un emploi', 3, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'les_professions_lesson_3'), 'flashcard', '{"front": "resume / CV", "back": "curriculum vitae / CV"}'::jsonb, 1, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'les_professions_lesson_3'), 'flashcard', '{"front": "job interview", "back": "entretien d''embauche"}'::jsonb, 2, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'les_professions_lesson_3'), 'translate_sentence', '{"prompt": "J''ai postulé à cinq emplois cette semaine.", "answer": "I applied for five jobs this week.", "hint": "postulé = applied, emplois = jobs"}'::jsonb, 3, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'les_professions_lesson_3'), 'fill_in_the_blank', '{"sentence": "I sent my ___ to three companies.", "answer": "resume", "options": ["resume", "meal", "table", "garden"]}'::jsonb, 4, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'les_professions_lesson_3'), 'word_reorder', '{"words": ["My", "interview", "is", "on", "Friday", "morning"], "answer": "My interview is on Friday morning"}'::jsonb, 5, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'les_professions_lesson_3'), 'true_or_false', '{"statement": "A lettre de motivation is a recommendation letter.", "answer": false, "explanation": "A lettre de motivation is a cover letter, not a recommendation letter"}'::jsonb, 6, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'les_professions_lesson_3'), 'listen_and_choose', '{"audio_text": "cover letter", "options": ["resume", "cover letter", "reference", "salary"], "answer": "cover letter"}'::jsonb, 7, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'les_professions_lesson_3'), 'select_correct_verb', '{"sentence": "She ___ for a job at the hospital.", "answer": "applied", "options": ["applied", "apply", "applying", "applies"]}'::jsonb, 8, 1, 10, true);

UPDATE modules SET
  slug              = 'au_bureau',
  title_al          = 'Au bureau',
  title_ll          = 'At the Office',
  description_al    = 'Naviguez dans le milieu professionnel : réunions, e-mails et gestion des priorités.',
  icon_name         = 'desktop',
  color_hex         = '#1ABC9C',
  difficulty_level  = 2,
  is_published      = true,
  xp_reward         = 100,
  estimated_minutes = 15
WHERE slug = 'shell_module_21';

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'au_bureau'), 'au_bureau_lesson_1', 'L''espace de travail', 1, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'au_bureau_lesson_1'), 'flashcard', '{"front": "printer", "back": "imprimante"}'::jsonb, 1, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'au_bureau_lesson_1'), 'flashcard', '{"front": "stapler", "back": "agrafeuse"}'::jsonb, 2, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'au_bureau_lesson_1'), 'translate_sentence', '{"prompt": "Le bureau de mon chef est au deuxième étage.", "answer": "My boss has an office on the second floor.", "hint": "étage = floor, deuxième = second"}'::jsonb, 3, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'au_bureau_lesson_1'), 'fill_in_the_blank', '{"sentence": "I need to print this on the ___.", "answer": "printer", "options": ["printer", "window", "calendar", "keyboard"]}'::jsonb, 4, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'au_bureau_lesson_1'), 'word_reorder', '{"words": ["My", "desk", "is", "near", "the", "window"], "answer": "My desk is near the window"}'::jsonb, 5, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'au_bureau_lesson_1'), 'true_or_false', '{"statement": "A salle de réunion is a bathroom.", "answer": false, "explanation": "A salle de réunion is a meeting room"}'::jsonb, 6, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'au_bureau_lesson_1'), 'listen_and_choose', '{"audio_text": "meeting room", "options": ["break room", "meeting room", "storage room", "mail room"], "answer": "meeting room"}'::jsonb, 7, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'au_bureau_lesson_1'), 'select_correct_verb', '{"sentence": "She ___ her computer on every morning.", "answer": "turns", "options": ["turns", "turn", "turned", "turning"]}'::jsonb, 8, 1, 10, true);

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'au_bureau'), 'au_bureau_lesson_2', 'Réunions et e-mails', 2, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'au_bureau_lesson_2'), 'flashcard', '{"front": "meeting", "back": "réunion"}'::jsonb, 1, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'au_bureau_lesson_2'), 'flashcard', '{"front": "agenda", "back": "ordre du jour"}'::jsonb, 2, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'au_bureau_lesson_2'), 'translate_sentence', '{"prompt": "Pouvez-vous planifier une réunion pour jeudi ?", "answer": "Can you schedule a meeting for Thursday?", "hint": "planifier = schedule, jeudi = Thursday"}'::jsonb, 3, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'au_bureau_lesson_2'), 'fill_in_the_blank', '{"sentence": "I need to ___ a meeting with the client.", "answer": "schedule", "options": ["schedule", "cancel", "sleep", "ignore"]}'::jsonb, 4, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'au_bureau_lesson_2'), 'word_reorder', '{"words": ["The", "meeting", "starts", "at", "nine"], "answer": "The meeting starts at nine"}'::jsonb, 5, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'au_bureau_lesson_2'), 'true_or_false', '{"statement": "CC in an email hides the recipients from each other.", "answer": false, "explanation": "CC shows all recipients; BCC hides them"}'::jsonb, 6, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'au_bureau_lesson_2'), 'listen_and_choose', '{"audio_text": "schedule a meeting", "options": ["cancel a meeting", "attend a meeting", "schedule a meeting", "miss a meeting"], "answer": "schedule a meeting"}'::jsonb, 7, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'au_bureau_lesson_2'), 'type_what_you_hear', '{"audio_text": "agenda", "answer": "agenda", "hint": "a list of topics for a meeting"}'::jsonb, 8, 1, 10, true);

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'au_bureau'), 'au_bureau_lesson_3', 'Les délais et les tâches', 3, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'au_bureau_lesson_3'), 'flashcard', '{"front": "deadline", "back": "délai / date limite"}'::jsonb, 1, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'au_bureau_lesson_3'), 'flashcard', '{"front": "task", "back": "tâche"}'::jsonb, 2, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'au_bureau_lesson_3'), 'translate_sentence', '{"prompt": "La date limite est vendredi prochain.", "answer": "The deadline is next Friday.", "hint": "date limite = deadline, vendredi = Friday"}'::jsonb, 3, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'au_bureau_lesson_3'), 'fill_in_the_blank', '{"sentence": "Can you finish this ___ by tomorrow?", "answer": "task", "options": ["task", "lunch", "chair", "window"]}'::jsonb, 4, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'au_bureau_lesson_3'), 'word_reorder', '{"words": ["The", "deadline", "is", "this", "Friday"], "answer": "The deadline is this Friday"}'::jsonb, 5, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'au_bureau_lesson_3'), 'true_or_false', '{"statement": "Being en retard means being ahead of schedule.", "answer": false, "explanation": "En retard means late or behind schedule"}'::jsonb, 6, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'au_bureau_lesson_3'), 'listen_and_choose', '{"audio_text": "the deadline is Friday", "options": ["the meeting is Friday", "the deadline is Friday", "the report is Friday", "the lunch is Friday"], "answer": "the deadline is Friday"}'::jsonb, 7, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'au_bureau_lesson_3'), 'select_correct_verb', '{"sentence": "She ___ all her tasks before noon.", "answer": "completes", "options": ["completes", "complete", "completing", "completed"]}'::jsonb, 8, 1, 10, true);

UPDATE modules SET
  slug              = 'ecole_universite',
  title_al          = 'À l''école et à l''université',
  title_ll          = 'School & University',
  description_al    = 'Vocabulaire essentiel pour naviguer dans le monde universitaire et scolaire.',
  icon_name         = 'school',
  color_hex         = '#F39C12',
  difficulty_level  = 2,
  is_published      = true,
  xp_reward         = 100,
  estimated_minutes = 15
WHERE slug = 'shell_module_22';

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'ecole_universite'), 'ecole_universite_lesson_1', 'S''inscrire à un cours', 1, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'ecole_universite_lesson_1'), 'flashcard', '{"front": "to register", "back": "s''inscrire"}'::jsonb, 1, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'ecole_universite_lesson_1'), 'flashcard', '{"front": "semester", "back": "semestre"}'::jsonb, 2, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'ecole_universite_lesson_1'), 'translate_sentence', '{"prompt": "Je dois m''inscrire avant la fin du mois.", "answer": "I need to register before the end of the month.", "hint": "m''inscrire = to register, fin = end"}'::jsonb, 3, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'ecole_universite_lesson_1'), 'fill_in_the_blank', '{"sentence": "I need to ___ for three classes this semester.", "answer": "register", "options": ["register", "forget", "eat", "arrive"]}'::jsonb, 4, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'ecole_universite_lesson_1'), 'word_reorder', '{"words": ["Registration", "opens", "on", "Monday", "morning"], "answer": "Registration opens on Monday morning"}'::jsonb, 5, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'ecole_universite_lesson_1'), 'true_or_false', '{"statement": "Semestre in French means year.", "answer": false, "explanation": "Semestre means semester, half a year, not a full year"}'::jsonb, 6, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'ecole_universite_lesson_1'), 'listen_and_choose', '{"audio_text": "registration deadline", "options": ["exam date", "registration deadline", "class schedule", "tuition fee"], "answer": "registration deadline"}'::jsonb, 7, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'ecole_universite_lesson_1'), 'select_correct_verb', '{"sentence": "She ___ for four courses last semester.", "answer": "registered", "options": ["registered", "registers", "register", "registering"]}'::jsonb, 8, 1, 10, true);

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'ecole_universite'), 'ecole_universite_lesson_2', 'La bibliothèque et les devoirs', 2, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'ecole_universite_lesson_2'), 'flashcard', '{"front": "assignment", "back": "devoir"}'::jsonb, 1, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'ecole_universite_lesson_2'), 'flashcard', '{"front": "library", "back": "bibliothèque"}'::jsonb, 2, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'ecole_universite_lesson_2'), 'translate_sentence', '{"prompt": "Je dois rendre mon devoir avant jeudi.", "answer": "I have to submit my assignment before Thursday.", "hint": "rendre = to submit, devoir = assignment"}'::jsonb, 3, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'ecole_universite_lesson_2'), 'fill_in_the_blank', '{"sentence": "I study at the ___ every evening.", "answer": "library", "options": ["library", "gym", "market", "park"]}'::jsonb, 4, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'ecole_universite_lesson_2'), 'word_reorder', '{"words": ["My", "assignment", "is", "due", "on", "Friday"], "answer": "My assignment is due on Friday"}'::jsonb, 5, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'ecole_universite_lesson_2'), 'true_or_false', '{"statement": "You submit an assignment, not give it.", "answer": true, "explanation": "The correct phrase is submit an assignment in academic English"}'::jsonb, 6, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'ecole_universite_lesson_2'), 'listen_and_choose', '{"audio_text": "submit your assignment", "options": ["write your assignment", "print your assignment", "submit your assignment", "lose your assignment"], "answer": "submit your assignment"}'::jsonb, 7, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'ecole_universite_lesson_2'), 'type_what_you_hear', '{"audio_text": "bibliography", "answer": "bibliography", "hint": "a list of sources used in a paper"}'::jsonb, 8, 1, 10, true);

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'ecole_universite'), 'ecole_universite_lesson_3', 'Parler à un professeur', 3, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'ecole_universite_lesson_3'), 'flashcard', '{"front": "grade", "back": "note"}'::jsonb, 1, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'ecole_universite_lesson_3'), 'flashcard', '{"front": "office hours", "back": "heures de permanence"}'::jsonb, 2, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'ecole_universite_lesson_3'), 'translate_sentence', '{"prompt": "Puis-je avoir vos heures de permanence ?", "answer": "Can I have your office hours, please?", "hint": "heures de permanence = office hours"}'::jsonb, 3, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'ecole_universite_lesson_3'), 'fill_in_the_blank', '{"sentence": "My ___ on the last exam was very good.", "answer": "grade", "options": ["grade", "lunch", "shirt", "table"]}'::jsonb, 4, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'ecole_universite_lesson_3'), 'word_reorder', '{"words": ["Can", "I", "ask", "you", "a", "question", "please"], "answer": "Can I ask you a question please"}'::jsonb, 5, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'ecole_universite_lesson_3'), 'true_or_false', '{"statement": "Office hours are times when the professor is unavailable.", "answer": false, "explanation": "Office hours are scheduled times when the professor is available to meet students"}'::jsonb, 6, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'ecole_universite_lesson_3'), 'listen_and_choose', '{"audio_text": "I have a question about the exam", "options": ["I need help with the library", "I have a question about the exam", "I want to change my grade", "I missed the class"], "answer": "I have a question about the exam"}'::jsonb, 7, 1, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'ecole_universite_lesson_3'), 'select_correct_verb', '{"sentence": "The professor ___ the exams back yesterday.", "answer": "gave", "options": ["gave", "give", "gives", "given"]}'::jsonb, 8, 1, 10, true);
