UPDATE modules SET
  slug              = 'transports_voyages',
  title_al          = 'Les transports et les voyages',
  title_ll          = 'Transport & Travel',
  description_al    = 'Voyagez en toute confiance : transports en commun, aéroport et hébergement.',
  icon_name         = 'airplane',
  color_hex         = '#2980B9',
  difficulty_level  = 3,
  is_published      = true,
  xp_reward         = 150,
  estimated_minutes = 20
WHERE slug = 'shell_module_26';

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'transports_voyages'), 'transports_voyages_lesson_1', 'Les transports en commun', 1, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'transports_voyages_lesson_1'), 'flashcard', '{"front": "bus stop", "back": "arrêt de bus"}'::jsonb, 1, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'transports_voyages_lesson_1'), 'flashcard', '{"front": "train ticket", "back": "billet de train"}'::jsonb, 2, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'transports_voyages_lesson_1'), 'translate_sentence', '{"prompt": "Je prends le métro pour aller au travail tous les jours.", "answer": "I take the metro to go to work every day.", "hint": "métro = metro, tous les jours = every day"}'::jsonb, 3, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'transports_voyages_lesson_1'), 'fill_in_the_blank', '{"sentence": "I need to buy a ___ for the train to Paris.", "answer": "ticket", "options": ["ticket", "sandwich", "jacket", "pencil"]}'::jsonb, 4, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'transports_voyages_lesson_1'), 'word_reorder', '{"words": ["The", "bus", "arrives", "every", "ten", "minutes"], "answer": "The bus arrives every ten minutes"}'::jsonb, 5, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'transports_voyages_lesson_1'), 'true_or_false', '{"statement": "The RER is a type of express train serving Paris and its suburbs.", "answer": true, "explanation": "The RER is the Réseau Express Régional, a rapid transit system in the Paris region"}'::jsonb, 6, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'transports_voyages_lesson_1'), 'listen_and_choose', '{"audio_text": "next train to Lyon", "options": ["next bus to Lyon", "next train to Lyon", "last train to Lyon", "direct train to Lyon"], "answer": "next train to Lyon"}'::jsonb, 7, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'transports_voyages_lesson_1'), 'select_correct_verb', '{"sentence": "She always ___ the metro to avoid traffic.", "answer": "takes", "options": ["takes", "take", "took", "taking"]}'::jsonb, 8, 2, 10, true);

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'transports_voyages'), 'transports_voyages_lesson_2', 'À l''aéroport', 2, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'transports_voyages_lesson_2'), 'flashcard', '{"front": "check-in", "back": "enregistrement"}'::jsonb, 1, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'transports_voyages_lesson_2'), 'flashcard', '{"front": "boarding pass", "back": "carte d''embarquement"}'::jsonb, 2, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'transports_voyages_lesson_2'), 'translate_sentence', '{"prompt": "Mon vol est retardé de deux heures.", "answer": "My flight is delayed by two hours.", "hint": "vol = flight, retardé = delayed"}'::jsonb, 3, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'transports_voyages_lesson_2'), 'fill_in_the_blank', '{"sentence": "I need to ___ my bags at the airport.", "answer": "check in", "options": ["check in", "cook", "sleep", "run"]}'::jsonb, 4, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'transports_voyages_lesson_2'), 'word_reorder', '{"words": ["My", "flight", "is", "delayed", "by", "one", "hour"], "answer": "My flight is delayed by one hour"}'::jsonb, 5, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'transports_voyages_lesson_2'), 'true_or_false', '{"statement": "Gate numbers are always printed on your ticket before check-in.", "answer": false, "explanation": "Gate numbers are usually displayed at the airport on the day of travel"}'::jsonb, 6, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'transports_voyages_lesson_2'), 'listen_and_choose', '{"audio_text": "your flight is now boarding", "options": ["your flight is delayed", "your flight is now boarding", "your flight is cancelled", "your flight is on time"], "answer": "your flight is now boarding"}'::jsonb, 7, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'transports_voyages_lesson_2'), 'type_what_you_hear', '{"audio_text": "boarding pass", "answer": "boarding pass", "hint": "the document you need to get on a plane"}'::jsonb, 8, 2, 10, true);

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'transports_voyages'), 'transports_voyages_lesson_3', 'À l''hôtel', 3, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'transports_voyages_lesson_3'), 'flashcard', '{"front": "room key", "back": "clé de chambre"}'::jsonb, 1, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'transports_voyages_lesson_3'), 'flashcard', '{"front": "check-out", "back": "départ / check-out"}'::jsonb, 2, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'transports_voyages_lesson_3'), 'translate_sentence', '{"prompt": "Je voudrais une chambre avec vue sur la mer.", "answer": "I would like a room with a sea view.", "hint": "chambre = room, vue sur la mer = sea view"}'::jsonb, 3, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'transports_voyages_lesson_3'), 'fill_in_the_blank', '{"sentence": "What time is ___?", "answer": "check-out", "options": ["check-out", "lunch", "gym", "pool"]}'::jsonb, 4, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'transports_voyages_lesson_3'), 'word_reorder', '{"words": ["I", "have", "a", "reservation", "for", "two", "nights"], "answer": "I have a reservation for two nights"}'::jsonb, 5, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'transports_voyages_lesson_3'), 'true_or_false', '{"statement": "Hotel check-out is typically around midday.", "answer": true, "explanation": "Most hotels set check-out time at 11am or 12pm, though policies vary"}'::jsonb, 6, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'transports_voyages_lesson_3'), 'listen_and_choose', '{"audio_text": "I have a reservation", "options": ["I need a room", "I have a reservation", "I want to cancel", "I need more towels"], "answer": "I have a reservation"}'::jsonb, 7, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'transports_voyages_lesson_3'), 'select_correct_verb', '{"sentence": "They ___ into the hotel late last night.", "answer": "checked", "options": ["checked", "check", "checking", "checks"]}'::jsonb, 8, 2, 10, true);

UPDATE modules SET
  slug              = 'logement',
  title_al          = 'Louer un logement',
  title_ll          = 'Renting Housing',
  description_al    = 'Cherchez un logement, signez un bail et communiquez avec votre propriétaire.',
  icon_name         = 'home',
  color_hex         = '#E67E22',
  difficulty_level  = 3,
  is_published      = true,
  xp_reward         = 150,
  estimated_minutes = 20
WHERE slug = 'shell_module_27';

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'logement'), 'logement_lesson_1', 'Chercher un logement', 1, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'logement_lesson_1'), 'flashcard', '{"front": "rent", "back": "loyer"}'::jsonb, 1, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'logement_lesson_1'), 'flashcard', '{"front": "deposit", "back": "caution"}'::jsonb, 2, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'logement_lesson_1'), 'translate_sentence', '{"prompt": "Le loyer est de huit cents euros par mois.", "answer": "The rent is eight hundred euros per month.", "hint": "loyer = rent, par mois = per month"}'::jsonb, 3, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'logement_lesson_1'), 'fill_in_the_blank', '{"sentence": "I am looking for a ___ with two bedrooms.", "answer": "flat", "options": ["flat", "boat", "factory", "farm"]}'::jsonb, 4, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'logement_lesson_1'), 'word_reorder', '{"words": ["The", "apartment", "is", "available", "from", "next", "month"], "answer": "The apartment is available from next month"}'::jsonb, 5, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'logement_lesson_1'), 'true_or_false', '{"statement": "Charges comprises means utilities are included in the rent.", "answer": true, "explanation": "Charges comprises means water, heating, and other utilities are included in the listed price"}'::jsonb, 6, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'logement_lesson_1'), 'listen_and_choose', '{"audio_text": "the deposit equals one month of rent", "options": ["the deposit is two months", "the deposit equals one month of rent", "there is no deposit", "the deposit is refundable"], "answer": "the deposit equals one month of rent"}'::jsonb, 7, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'logement_lesson_1'), 'select_correct_verb', '{"sentence": "She ___ for apartments online every evening.", "answer": "searches", "options": ["searches", "search", "searched", "searching"]}'::jsonb, 8, 2, 10, true);

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'logement'), 'logement_lesson_2', 'Signer un bail', 2, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'logement_lesson_2'), 'flashcard', '{"front": "lease", "back": "bail"}'::jsonb, 1, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'logement_lesson_2'), 'flashcard', '{"front": "landlord", "back": "propriétaire"}'::jsonb, 2, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'logement_lesson_2'), 'translate_sentence', '{"prompt": "Le bail est pour une durée d''un an.", "answer": "The lease is for one year.", "hint": "durée = duration, un an = one year"}'::jsonb, 3, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'logement_lesson_2'), 'fill_in_the_blank', '{"sentence": "I need to sign the ___ before moving in.", "answer": "lease", "options": ["lease", "meal", "book", "curtain"]}'::jsonb, 4, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'logement_lesson_2'), 'word_reorder', '{"words": ["The", "lease", "starts", "on", "the", "first", "of", "May"], "answer": "The lease starts on the first of May"}'::jsonb, 5, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'logement_lesson_2'), 'true_or_false', '{"statement": "In France you can break a lease without giving any notice.", "answer": false, "explanation": "In France you typically need to give one to three months of notice to end a lease"}'::jsonb, 6, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'logement_lesson_2'), 'listen_and_choose', '{"audio_text": "give one month of notice", "options": ["sign the lease again", "give one month of notice", "pay a new deposit", "contact an agent"], "answer": "give one month of notice"}'::jsonb, 7, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'logement_lesson_2'), 'type_what_you_hear', '{"audio_text": "landlord", "answer": "landlord", "hint": "the person who owns and rents out a property"}'::jsonb, 8, 2, 10, true);

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'logement'), 'logement_lesson_3', 'Parler au propriétaire', 3, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'logement_lesson_3'), 'flashcard', '{"front": "repair", "back": "réparation"}'::jsonb, 1, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'logement_lesson_3'), 'flashcard', '{"front": "heating", "back": "chauffage"}'::jsonb, 2, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'logement_lesson_3'), 'translate_sentence', '{"prompt": "Le chauffage est en panne depuis trois jours.", "answer": "The heating has been broken for three days.", "hint": "en panne = broken, depuis = for/since"}'::jsonb, 3, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'logement_lesson_3'), 'fill_in_the_blank', '{"sentence": "The ___ in the flat is broken, can you fix it?", "answer": "heating", "options": ["heating", "pizza", "lamp", "book"]}'::jsonb, 4, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'logement_lesson_3'), 'word_reorder', '{"words": ["The", "heating", "has", "been", "broken", "since", "Monday"], "answer": "The heating has been broken since Monday"}'::jsonb, 5, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'logement_lesson_3'), 'true_or_false', '{"statement": "The tenant is responsible for all major repairs in a French rental.", "answer": false, "explanation": "Major repairs are the landlord''s responsibility; tenants only handle minor upkeep"}'::jsonb, 6, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'logement_lesson_3'), 'listen_and_choose', '{"audio_text": "the heating is broken", "options": ["the window is broken", "the heating is broken", "the lock is broken", "the pipe is broken"], "answer": "the heating is broken"}'::jsonb, 7, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'logement_lesson_3'), 'select_correct_verb', '{"sentence": "She ___ her landlord to report the broken boiler.", "answer": "called", "options": ["called", "call", "calls", "calling"]}'::jsonb, 8, 2, 10, true);

UPDATE modules SET
  slug              = 'vie_sociale_professionnelle',
  title_al          = 'La vie sociale et professionnelle',
  title_ll          = 'Social & Professional Life',
  description_al    = 'Développez votre réseau professionnel et maîtrisez les codes sociaux en anglais.',
  icon_name         = 'people',
  color_hex         = '#8E44AD',
  difficulty_level  = 3,
  is_published      = true,
  xp_reward         = 150,
  estimated_minutes = 20
WHERE slug = 'shell_module_28';

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'vie_sociale_professionnelle'), 'vie_sociale_professionnelle_lesson_1', 'Le réseautage', 1, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'vie_sociale_professionnelle_lesson_1'), 'flashcard', '{"front": "networking", "back": "réseautage"}'::jsonb, 1, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'vie_sociale_professionnelle_lesson_1'), 'flashcard', '{"front": "business card", "back": "carte de visite"}'::jsonb, 2, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'vie_sociale_professionnelle_lesson_1'), 'translate_sentence', '{"prompt": "C''est un plaisir de vous rencontrer lors de cet événement.", "answer": "It is a pleasure to meet you at this event.", "hint": "plaisir = pleasure, rencontrer = meet"}'::jsonb, 3, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'vie_sociale_professionnelle_lesson_1'), 'fill_in_the_blank', '{"sentence": "Let me give you my ___.", "answer": "business card", "options": ["business card", "homework", "lunch", "remote"]}'::jsonb, 4, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'vie_sociale_professionnelle_lesson_1'), 'word_reorder', '{"words": ["It", "is", "nice", "to", "meet", "you"], "answer": "It is nice to meet you"}'::jsonb, 5, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'vie_sociale_professionnelle_lesson_1'), 'true_or_false', '{"statement": "Small talk about the weather is inappropriate at professional events.", "answer": false, "explanation": "Small talk about neutral topics like the weather is common and acceptable in professional settings"}'::jsonb, 6, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'vie_sociale_professionnelle_lesson_1'), 'listen_and_choose', '{"audio_text": "let us grab coffee sometime", "options": ["let us schedule a meeting", "let us grab coffee sometime", "let us exchange contracts", "let us call it a day"], "answer": "let us grab coffee sometime"}'::jsonb, 7, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'vie_sociale_professionnelle_lesson_1'), 'select_correct_verb', '{"sentence": "She ___ her network by attending industry events.", "answer": "builds", "options": ["builds", "build", "built", "building"]}'::jsonb, 8, 2, 10, true);

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'vie_sociale_professionnelle'), 'vie_sociale_professionnelle_lesson_2', 'Accepter ou refuser une invitation', 2, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'vie_sociale_professionnelle_lesson_2'), 'flashcard', '{"front": "invitation", "back": "invitation"}'::jsonb, 1, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'vie_sociale_professionnelle_lesson_2'), 'flashcard', '{"front": "to decline", "back": "refuser / décliner"}'::jsonb, 2, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'vie_sociale_professionnelle_lesson_2'), 'translate_sentence', '{"prompt": "Je suis désolé, je ne pourrai pas venir vendredi soir.", "answer": "I am sorry, I will not be able to come on Friday evening.", "hint": "désolé = sorry, pourrai = will be able to"}'::jsonb, 3, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'vie_sociale_professionnelle_lesson_2'), 'fill_in_the_blank', '{"sentence": "Thank you for the invitation, but I have to ___.", "answer": "decline", "options": ["decline", "eat", "sleep", "travel"]}'::jsonb, 4, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'vie_sociale_professionnelle_lesson_2'), 'word_reorder', '{"words": ["I", "would", "love", "to", "come", "to", "your", "party"], "answer": "I would love to come to your party"}'::jsonb, 5, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'vie_sociale_professionnelle_lesson_2'), 'true_or_false', '{"statement": "It is polite to give a reason when declining an invitation.", "answer": true, "explanation": "Giving a brief reason when declining shows respect and consideration for the host"}'::jsonb, 6, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'vie_sociale_professionnelle_lesson_2'), 'listen_and_choose', '{"audio_text": "I am afraid I cannot make it", "options": ["I would love to come", "I am afraid I cannot make it", "I will be a little late", "I am not sure yet"], "answer": "I am afraid I cannot make it"}'::jsonb, 7, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'vie_sociale_professionnelle_lesson_2'), 'type_what_you_hear', '{"audio_text": "decline", "answer": "decline", "hint": "to say no to an invitation politely"}'::jsonb, 8, 2, 10, true);

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'vie_sociale_professionnelle'), 'vie_sociale_professionnelle_lesson_3', 'La culture professionnelle', 3, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'vie_sociale_professionnelle_lesson_3'), 'flashcard', '{"front": "work-life balance", "back": "équilibre travail-vie personnelle"}'::jsonb, 1, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'vie_sociale_professionnelle_lesson_3'), 'flashcard', '{"front": "handshake", "back": "poignée de main"}'::jsonb, 2, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'vie_sociale_professionnelle_lesson_3'), 'translate_sentence', '{"prompt": "Il est important de respecter les horaires de travail.", "answer": "It is important to respect working hours.", "hint": "respecter = to respect, horaires = schedule/hours"}'::jsonb, 3, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'vie_sociale_professionnelle_lesson_3'), 'fill_in_the_blank', '{"sentence": "It is important to greet your ___ every morning.", "answer": "colleagues", "options": ["colleagues", "furniture", "customers", "plants"]}'::jsonb, 4, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'vie_sociale_professionnelle_lesson_3'), 'word_reorder', '{"words": ["Let", "us", "grab", "coffee", "after", "the", "meeting"], "answer": "Let us grab coffee after the meeting"}'::jsonb, 5, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'vie_sociale_professionnelle_lesson_3'), 'true_or_false', '{"statement": "In France, it is common to shake hands when greeting a colleague.", "answer": true, "explanation": "A handshake is a standard professional greeting in France"}'::jsonb, 6, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'vie_sociale_professionnelle_lesson_3'), 'listen_and_choose', '{"audio_text": "shall we grab lunch?", "options": ["shall we have a meeting?", "shall we grab lunch?", "shall we go home?", "shall we start work?"], "answer": "shall we grab lunch?"}'::jsonb, 7, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'vie_sociale_professionnelle_lesson_3'), 'select_correct_verb', '{"sentence": "He always ___ his colleagues a good morning.", "answer": "wishes", "options": ["wishes", "wish", "wished", "wishing"]}'::jsonb, 8, 2, 10, true);
