UPDATE modules SET
  slug              = 'medecin_pharmacie',
  title_al          = 'Chez le médecin et à la pharmacie',
  title_ll          = 'Doctor & Pharmacy',
  description_al    = 'Prenez rendez-vous, décrivez vos symptômes et communiquez à la pharmacie.',
  icon_name         = 'medkit',
  color_hex         = '#C0392B',
  difficulty_level  = 3,
  is_published      = true,
  xp_reward         = 150,
  estimated_minutes = 20
WHERE slug = 'shell_module_23';

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'medecin_pharmacie'), 'medecin_pharmacie_lesson_1', 'Prendre rendez-vous', 1, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'medecin_pharmacie_lesson_1'), 'flashcard', '{"front": "appointment", "back": "rendez-vous"}'::jsonb, 1, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'medecin_pharmacie_lesson_1'), 'flashcard', '{"front": "waiting room", "back": "salle d''attente"}'::jsonb, 2, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'medecin_pharmacie_lesson_1'), 'translate_sentence', '{"prompt": "Je voudrais prendre un rendez-vous pour mardi.", "answer": "I would like to make an appointment for Tuesday.", "hint": "prendre un rendez-vous = make an appointment, mardi = Tuesday"}'::jsonb, 3, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'medecin_pharmacie_lesson_1'), 'fill_in_the_blank', '{"sentence": "I need to ___ an appointment with my doctor.", "answer": "make", "options": ["make", "lose", "cancel", "forget"]}'::jsonb, 4, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'medecin_pharmacie_lesson_1'), 'word_reorder', '{"words": ["My", "appointment", "is", "at", "two", "pm"], "answer": "My appointment is at two pm"}'::jsonb, 5, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'medecin_pharmacie_lesson_1'), 'true_or_false', '{"statement": "Je voudrais un rendez-vous is a polite way to book an appointment in French.", "answer": true, "explanation": "This phrase is correct and polite for requesting an appointment"}'::jsonb, 6, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'medecin_pharmacie_lesson_1'), 'listen_and_choose', '{"audio_text": "I need to make an appointment", "options": ["I need to cancel an appointment", "I need to make an appointment", "I need to see a specialist", "I need a prescription"], "answer": "I need to make an appointment"}'::jsonb, 7, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'medecin_pharmacie_lesson_1'), 'select_correct_verb', '{"sentence": "She always ___ her appointments in advance.", "answer": "books", "options": ["books", "book", "booked", "booking"]}'::jsonb, 8, 2, 10, true);

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'medecin_pharmacie'), 'medecin_pharmacie_lesson_2', 'Décrire ses symptômes', 2, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'medecin_pharmacie_lesson_2'), 'flashcard', '{"front": "headache", "back": "mal de tête"}'::jsonb, 1, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'medecin_pharmacie_lesson_2'), 'flashcard', '{"front": "fever", "back": "fièvre"}'::jsonb, 2, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'medecin_pharmacie_lesson_2'), 'translate_sentence', '{"prompt": "J''ai mal à la gorge et j''ai de la fièvre depuis hier.", "answer": "I have a sore throat and I have had a fever since yesterday.", "hint": "mal à la gorge = sore throat, depuis = since"}'::jsonb, 3, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'medecin_pharmacie_lesson_2'), 'fill_in_the_blank', '{"sentence": "I have a bad ___ and I feel dizzy.", "answer": "headache", "options": ["headache", "schedule", "meeting", "breakfast"]}'::jsonb, 4, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'medecin_pharmacie_lesson_2'), 'word_reorder', '{"words": ["I", "have", "had", "a", "fever", "since", "yesterday"], "answer": "I have had a fever since yesterday"}'::jsonb, 5, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'medecin_pharmacie_lesson_2'), 'true_or_false', '{"statement": "Mal au ventre means headache.", "answer": false, "explanation": "Mal au ventre means stomachache; mal de tête means headache"}'::jsonb, 6, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'medecin_pharmacie_lesson_2'), 'listen_and_choose', '{"audio_text": "I have a sore throat", "options": ["I have a headache", "I have a sore throat", "I have a stomach ache", "I have a fever"], "answer": "I have a sore throat"}'::jsonb, 7, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'medecin_pharmacie_lesson_2'), 'type_what_you_hear', '{"audio_text": "symptom", "answer": "symptom", "hint": "a sign of illness your doctor asks about"}'::jsonb, 8, 2, 10, true);

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'medecin_pharmacie'), 'medecin_pharmacie_lesson_3', 'À la pharmacie', 3, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'medecin_pharmacie_lesson_3'), 'flashcard', '{"front": "prescription", "back": "ordonnance"}'::jsonb, 1, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'medecin_pharmacie_lesson_3'), 'flashcard', '{"front": "painkiller", "back": "analgésique / antidouleur"}'::jsonb, 2, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'medecin_pharmacie_lesson_3'), 'translate_sentence', '{"prompt": "J''ai besoin de médicaments pour la toux.", "answer": "I need medicine for the cough.", "hint": "médicaments = medicine, toux = cough"}'::jsonb, 3, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'medecin_pharmacie_lesson_3'), 'fill_in_the_blank', '{"sentence": "The doctor gave me a ___ for antibiotics.", "answer": "prescription", "options": ["prescription", "ticket", "receipt", "card"]}'::jsonb, 4, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'medecin_pharmacie_lesson_3'), 'word_reorder', '{"words": ["Do", "you", "have", "anything", "for", "a", "cold"], "answer": "Do you have anything for a cold"}'::jsonb, 5, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'medecin_pharmacie_lesson_3'), 'true_or_false', '{"statement": "You need a prescription for all medicines in France.", "answer": false, "explanation": "Many medicines are available over the counter in France"}'::jsonb, 6, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'medecin_pharmacie_lesson_3'), 'listen_and_choose', '{"audio_text": "Do you have anything for a headache?", "options": ["Do you have a prescription?", "Do you have anything for a headache?", "Do you sell vitamins?", "Is the pharmacy open?"], "answer": "Do you have anything for a headache?"}'::jsonb, 7, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'medecin_pharmacie_lesson_3'), 'type_what_you_hear', '{"audio_text": "prescription", "answer": "prescription", "hint": "a written order from a doctor for medicine"}'::jsonb, 8, 2, 10, true);

UPDATE modules SET
  slug              = 'demarches_administratives',
  title_al          = 'Les démarches administratives',
  title_ll          = 'Admin & Paperwork',
  description_al    = 'Remplissez des formulaires et effectuez vos démarches administratives en anglais.',
  icon_name         = 'document-text',
  color_hex         = '#7F8C8D',
  difficulty_level  = 3,
  is_published      = true,
  xp_reward         = 150,
  estimated_minutes = 20
WHERE slug = 'shell_module_24';

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'demarches_administratives'), 'demarches_administratives_lesson_1', 'Remplir un formulaire', 1, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'demarches_administratives_lesson_1'), 'flashcard', '{"front": "form", "back": "formulaire"}'::jsonb, 1, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'demarches_administratives_lesson_1'), 'flashcard', '{"front": "to fill out", "back": "remplir"}'::jsonb, 2, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'demarches_administratives_lesson_1'), 'translate_sentence', '{"prompt": "Vous devez remplir ce formulaire en lettres majuscules.", "answer": "You must fill out this form in capital letters.", "hint": "lettres majuscules = capital letters"}'::jsonb, 3, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'demarches_administratives_lesson_1'), 'fill_in_the_blank', '{"sentence": "Please ___ this form and sign at the bottom.", "answer": "fill out", "options": ["fill out", "throw away", "ignore", "tear up"]}'::jsonb, 4, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'demarches_administratives_lesson_1'), 'word_reorder', '{"words": ["I", "need", "to", "fill", "out", "this", "form"], "answer": "I need to fill out this form"}'::jsonb, 5, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'demarches_administratives_lesson_1'), 'true_or_false', '{"statement": "Nom on a French form is where you write your first name.", "answer": false, "explanation": "Nom is your family name; your first name goes in Prénom"}'::jsonb, 6, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'demarches_administratives_lesson_1'), 'listen_and_choose', '{"audio_text": "sign here please", "options": ["wait here please", "sign here please", "leave here please", "sit here please"], "answer": "sign here please"}'::jsonb, 7, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'demarches_administratives_lesson_1'), 'select_correct_verb', '{"sentence": "She ___ the form incorrectly and had to start over.", "answer": "filled", "options": ["filled", "fill", "filling", "fills"]}'::jsonb, 8, 2, 10, true);

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'demarches_administratives'), 'demarches_administratives_lesson_2', 'Les documents d''identité', 2, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'demarches_administratives_lesson_2'), 'flashcard', '{"front": "ID card", "back": "carte d''identité"}'::jsonb, 1, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'demarches_administratives_lesson_2'), 'flashcard', '{"front": "residence permit", "back": "titre de séjour"}'::jsonb, 2, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'demarches_administratives_lesson_2'), 'translate_sentence', '{"prompt": "Vous avez besoin d''une pièce d''identité pour ouvrir un compte.", "answer": "You need an ID document to open an account.", "hint": "pièce d''identité = identity document"}'::jsonb, 3, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'demarches_administratives_lesson_2'), 'fill_in_the_blank', '{"sentence": "I need to renew my ___ before it expires.", "answer": "passport", "options": ["passport", "spoon", "shirt", "bottle"]}'::jsonb, 4, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'demarches_administratives_lesson_2'), 'word_reorder', '{"words": ["Can", "I", "see", "your", "ID", "please"], "answer": "Can I see your ID please"}'::jsonb, 5, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'demarches_administratives_lesson_2'), 'true_or_false', '{"statement": "A titre de séjour is a tourist visa.", "answer": false, "explanation": "A titre de séjour is a residence permit for long-term stays, not a tourist visa"}'::jsonb, 6, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'demarches_administratives_lesson_2'), 'listen_and_choose', '{"audio_text": "residence permit", "options": ["driving licence", "residence permit", "student card", "health card"], "answer": "residence permit"}'::jsonb, 7, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'demarches_administratives_lesson_2'), 'type_what_you_hear', '{"audio_text": "identity", "answer": "identity", "hint": "what documents prove about you"}'::jsonb, 8, 2, 10, true);

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'demarches_administratives'), 'demarches_administratives_lesson_3', 'Au bureau administratif', 3, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'demarches_administratives_lesson_3'), 'flashcard', '{"front": "counter", "back": "guichet"}'::jsonb, 1, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'demarches_administratives_lesson_3'), 'flashcard', '{"front": "ticket number", "back": "numéro de ticket"}'::jsonb, 2, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'demarches_administratives_lesson_3'), 'translate_sentence', '{"prompt": "Quel document dois-je apporter pour ce rendez-vous ?", "answer": "What document do I need to bring for this appointment?", "hint": "apporter = to bring"}'::jsonb, 3, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'demarches_administratives_lesson_3'), 'fill_in_the_blank', '{"sentence": "Please take a ___ and wait to be called.", "answer": "number", "options": ["number", "sandwich", "book", "pen"]}'::jsonb, 4, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'demarches_administratives_lesson_3'), 'word_reorder', '{"words": ["What", "documents", "do", "I", "need", "to", "bring"], "answer": "What documents do I need to bring"}'::jsonb, 5, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'demarches_administratives_lesson_3'), 'true_or_false', '{"statement": "In France, you always need to book an appointment at government offices.", "answer": false, "explanation": "Some offices accept walk-ins; others require appointments — it varies by service"}'::jsonb, 6, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'demarches_administratives_lesson_3'), 'listen_and_choose', '{"audio_text": "please take a number", "options": ["please take a seat", "please take a number", "please show your ID", "please sign the form"], "answer": "please take a number"}'::jsonb, 7, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'demarches_administratives_lesson_3'), 'select_correct_verb', '{"sentence": "He ___ at the counter and explained his situation.", "answer": "arrived", "options": ["arrived", "arrive", "arrives", "arriving"]}'::jsonb, 8, 2, 10, true);

UPDATE modules SET
  slug              = 'banque_finances',
  title_al          = 'Banque et finances personnelles',
  title_ll          = 'Banking & Personal Finance',
  description_al    = 'Gérez vos finances : ouvrir un compte, effectuer des virements et lire vos relevés.',
  icon_name         = 'cash',
  color_hex         = '#27AE60',
  difficulty_level  = 3,
  is_published      = true,
  xp_reward         = 150,
  estimated_minutes = 20
WHERE slug = 'shell_module_25';

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'banque_finances'), 'banque_finances_lesson_1', 'Ouvrir un compte bancaire', 1, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'banque_finances_lesson_1'), 'flashcard', '{"front": "bank account", "back": "compte bancaire"}'::jsonb, 1, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'banque_finances_lesson_1'), 'flashcard', '{"front": "bank statement", "back": "relevé de compte"}'::jsonb, 2, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'banque_finances_lesson_1'), 'translate_sentence', '{"prompt": "Je voudrais ouvrir un compte courant.", "answer": "I would like to open a current account.", "hint": "compte courant = current account"}'::jsonb, 3, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'banque_finances_lesson_1'), 'fill_in_the_blank', '{"sentence": "I need to open a ___ account at the bank.", "answer": "savings", "options": ["savings", "soup", "garden", "paper"]}'::jsonb, 4, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'banque_finances_lesson_1'), 'word_reorder', '{"words": ["I", "would", "like", "to", "open", "a", "bank", "account"], "answer": "I would like to open a bank account"}'::jsonb, 5, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'banque_finances_lesson_1'), 'true_or_false', '{"statement": "A RIB contains your IBAN and bank details needed for transfers.", "answer": true, "explanation": "A RIB contains your IBAN and other account details needed for transfers"}'::jsonb, 6, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'banque_finances_lesson_1'), 'listen_and_choose', '{"audio_text": "I need to open an account", "options": ["I need to close my account", "I need to open an account", "I need to transfer money", "I need a credit card"], "answer": "I need to open an account"}'::jsonb, 7, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'banque_finances_lesson_1'), 'type_what_you_hear', '{"audio_text": "bank statement", "answer": "bank statement", "hint": "a monthly summary of your account activity"}'::jsonb, 8, 2, 10, true);

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'banque_finances'), 'banque_finances_lesson_2', 'Les transactions bancaires', 2, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'banque_finances_lesson_2'), 'flashcard', '{"front": "transfer", "back": "virement"}'::jsonb, 1, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'banque_finances_lesson_2'), 'flashcard', '{"front": "declined", "back": "refusé / refusée"}'::jsonb, 2, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'banque_finances_lesson_2'), 'translate_sentence', '{"prompt": "Ma carte a été refusée au supermarché ce matin.", "answer": "My card was declined at the supermarket this morning.", "hint": "refusée = declined, supermarché = supermarket"}'::jsonb, 3, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'banque_finances_lesson_2'), 'fill_in_the_blank', '{"sentence": "I need to ___ money to my landlord by the first of the month.", "answer": "transfer", "options": ["transfer", "lose", "forget", "delay"]}'::jsonb, 4, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'banque_finances_lesson_2'), 'word_reorder', '{"words": ["My", "card", "was", "declined", "at", "the", "store"], "answer": "My card was declined at the store"}'::jsonb, 5, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'banque_finances_lesson_2'), 'true_or_false', '{"statement": "A virement bancaire is a bank transfer.", "answer": true, "explanation": "Virement bancaire means bank transfer in French"}'::jsonb, 6, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'banque_finances_lesson_2'), 'listen_and_choose', '{"audio_text": "my card was declined", "options": ["my card was stolen", "my card was declined", "my card expired", "my card is lost"], "answer": "my card was declined"}'::jsonb, 7, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'banque_finances_lesson_2'), 'select_correct_verb', '{"sentence": "She ___ the bill online last night.", "answer": "paid", "options": ["paid", "pay", "pays", "paying"]}'::jsonb, 8, 2, 10, true);

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'banque_finances'), 'banque_finances_lesson_3', 'Comprendre une lettre bancaire', 3, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'banque_finances_lesson_3'), 'flashcard', '{"front": "direct debit", "back": "prélèvement automatique"}'::jsonb, 1, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'banque_finances_lesson_3'), 'flashcard', '{"front": "overdraft", "back": "découvert"}'::jsonb, 2, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'banque_finances_lesson_3'), 'translate_sentence', '{"prompt": "Votre compte est à découvert de cinquante euros.", "answer": "Your account is overdrawn by fifty euros.", "hint": "à découvert = overdrawn, cinquante = fifty"}'::jsonb, 3, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'banque_finances_lesson_3'), 'fill_in_the_blank', '{"sentence": "I set up a ___ to pay my rent automatically.", "answer": "direct debit", "options": ["direct debit", "postcard", "garden", "alarm"]}'::jsonb, 4, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'banque_finances_lesson_3'), 'word_reorder', '{"words": ["I", "received", "a", "letter", "from", "my", "bank"], "answer": "I received a letter from my bank"}'::jsonb, 5, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'banque_finances_lesson_3'), 'true_or_false', '{"statement": "An overdraft means you have extra money in your account.", "answer": false, "explanation": "An overdraft means your balance is negative and you owe money"}'::jsonb, 6, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'banque_finances_lesson_3'), 'listen_and_choose', '{"audio_text": "your account is overdrawn", "options": ["your account is closed", "your account is overdrawn", "your account is frozen", "your account is full"], "answer": "your account is overdrawn"}'::jsonb, 7, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'banque_finances_lesson_3'), 'type_what_you_hear', '{"audio_text": "overdraft", "answer": "overdraft", "hint": "when your account balance goes below zero"}'::jsonb, 8, 2, 10, true);
