UPDATE modules SET
  slug              = 'citoyennete_droits',
  title_al          = 'La citoyenneté et les droits',
  title_ll          = 'Citizenship & Rights',
  description_al    = 'Comprenez vos droits et vos responsabilités en tant que résident en anglais.',
  icon_name         = 'ribbon',
  color_hex         = '#2C3E50',
  difficulty_level  = 3,
  is_published      = true,
  xp_reward         = 150,
  estimated_minutes = 20
WHERE slug = 'shell_module_29';

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'citoyennete_droits'), 'citoyennete_droits_lesson_1', 'Les droits et les responsabilités', 1, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'citoyennete_droits_lesson_1'), 'flashcard', '{"front": "right", "back": "droit"}'::jsonb, 1, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'citoyennete_droits_lesson_1'), 'flashcard', '{"front": "responsibility", "back": "responsabilité"}'::jsonb, 2, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'citoyennete_droits_lesson_1'), 'translate_sentence', '{"prompt": "Chaque citoyen a le droit de voter.", "answer": "Every citizen has the right to vote.", "hint": "citoyen = citizen, voter = to vote"}'::jsonb, 3, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'citoyennete_droits_lesson_1'), 'fill_in_the_blank', '{"sentence": "You have the right to remain ___ if arrested.", "answer": "silent", "options": ["silent", "loud", "happy", "busy"]}'::jsonb, 4, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'citoyennete_droits_lesson_1'), 'word_reorder', '{"words": ["Every", "citizen", "has", "rights", "and", "responsibilities"], "answer": "Every citizen has rights and responsibilities"}'::jsonb, 5, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'citoyennete_droits_lesson_1'), 'true_or_false', '{"statement": "Paying taxes is a civic responsibility.", "answer": true, "explanation": "Tax payment is a legal responsibility that funds public services"}'::jsonb, 6, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'citoyennete_droits_lesson_1'), 'listen_and_choose', '{"audio_text": "the right to vote", "options": ["the right to travel", "the right to vote", "the right to work", "the right to speak"], "answer": "the right to vote"}'::jsonb, 7, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'citoyennete_droits_lesson_1'), 'select_correct_verb', '{"sentence": "She ___ her civic duties seriously.", "answer": "takes", "options": ["takes", "take", "took", "taking"]}'::jsonb, 8, 2, 10, true);

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'citoyennete_droits'), 'citoyennete_droits_lesson_2', 'Les services communautaires', 2, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'citoyennete_droits_lesson_2'), 'flashcard', '{"front": "community centre", "back": "centre communautaire"}'::jsonb, 1, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'citoyennete_droits_lesson_2'), 'flashcard', '{"front": "social worker", "back": "assistant social / assistante sociale"}'::jsonb, 2, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'citoyennete_droits_lesson_2'), 'translate_sentence', '{"prompt": "Comment puis-je m''inscrire sur les listes électorales ?", "answer": "How can I register on the electoral rolls?", "hint": "listes électorales = electoral rolls"}'::jsonb, 3, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'citoyennete_droits_lesson_2'), 'fill_in_the_blank', '{"sentence": "The ___ can help you find housing support.", "answer": "social worker", "options": ["social worker", "bus driver", "chef", "postman"]}'::jsonb, 4, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'citoyennete_droits_lesson_2'), 'word_reorder', '{"words": ["How", "do", "I", "register", "to", "vote"], "answer": "How do I register to vote"}'::jsonb, 5, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'citoyennete_droits_lesson_2'), 'true_or_false', '{"statement": "A mairie is a post office.", "answer": false, "explanation": "A mairie is a town hall where many civic services are provided"}'::jsonb, 6, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'citoyennete_droits_lesson_2'), 'listen_and_choose', '{"audio_text": "how do I register?", "options": ["how do I complain?", "how do I register?", "how do I pay?", "how do I leave?"], "answer": "how do I register?"}'::jsonb, 7, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'citoyennete_droits_lesson_2'), 'type_what_you_hear', '{"audio_text": "register", "answer": "register", "hint": "to sign up officially for something"}'::jsonb, 8, 2, 10, true);

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'citoyennete_droits'), 'citoyennete_droits_lesson_3', 'Interagir avec les autorités', 3, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'citoyennete_droits_lesson_3'), 'flashcard', '{"front": "police officer", "back": "agent de police"}'::jsonb, 1, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'citoyennete_droits_lesson_3'), 'flashcard', '{"front": "official letter", "back": "courrier officiel"}'::jsonb, 2, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'citoyennete_droits_lesson_3'), 'translate_sentence', '{"prompt": "Puis-je vous demander pourquoi vous m''arrêtez ?", "answer": "May I ask why you are stopping me?", "hint": "arrêtez = stopping, pourquoi = why"}'::jsonb, 3, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'citoyennete_droits_lesson_3'), 'fill_in_the_blank', '{"sentence": "I received an ___ letter from the prefecture.", "answer": "official", "options": ["official", "friendly", "short", "funny"]}'::jsonb, 4, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'citoyennete_droits_lesson_3'), 'word_reorder', '{"words": ["I", "do", "not", "understand", "this", "letter"], "answer": "I do not understand this letter"}'::jsonb, 5, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'citoyennete_droits_lesson_3'), 'true_or_false', '{"statement": "In France, you must prove your identity if asked by police.", "answer": true, "explanation": "In France you are legally required to prove your identity if asked by police"}'::jsonb, 6, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'citoyennete_droits_lesson_3'), 'listen_and_choose', '{"audio_text": "can I see your ID please?", "options": ["can I help you?", "can I see your ID please?", "where are you going?", "do you speak French?"], "answer": "can I see your ID please?"}'::jsonb, 7, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'citoyennete_droits_lesson_3'), 'select_correct_verb', '{"sentence": "He ___ politely and showed his residence permit.", "answer": "responded", "options": ["responded", "respond", "responds", "responding"]}'::jsonb, 8, 2, 10, true);

UPDATE modules SET
  slug              = 'revision_conversation',
  title_al          = 'Révision et conversation libre',
  title_ll          = 'Review & Free Conversation',
  description_al    = 'Mettez en pratique tout ce que vous avez appris dans des situations réelles.',
  icon_name         = 'chatbubbles',
  color_hex         = '#16A085',
  difficulty_level  = 3,
  is_published      = true,
  xp_reward         = 150,
  estimated_minutes = 20
WHERE slug = 'shell_module_30';

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'revision_conversation'), 'revision_conversation_lesson_1', 'L''entretien d''embauche', 1, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'revision_conversation_lesson_1'), 'flashcard', '{"front": "strengths", "back": "points forts"}'::jsonb, 1, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'revision_conversation_lesson_1'), 'flashcard', '{"front": "weaknesses", "back": "points faibles"}'::jsonb, 2, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'revision_conversation_lesson_1'), 'translate_sentence', '{"prompt": "Pouvez-vous me parler de votre expérience professionnelle ?", "answer": "Can you tell me about your professional experience?", "hint": "expérience professionnelle = professional experience"}'::jsonb, 3, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'revision_conversation_lesson_1'), 'fill_in_the_blank', '{"sentence": "My greatest ___ is my ability to work under pressure.", "answer": "strength", "options": ["strength", "colour", "meal", "vehicle"]}'::jsonb, 4, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'revision_conversation_lesson_1'), 'word_reorder', '{"words": ["I", "am", "very", "motivated", "and", "organized"], "answer": "I am very motivated and organized"}'::jsonb, 5, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'revision_conversation_lesson_1'), 'true_or_false', '{"statement": "You should always research the company before a job interview.", "answer": true, "explanation": "Researching the company shows initiative and helps you answer questions confidently"}'::jsonb, 6, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'revision_conversation_lesson_1'), 'listen_and_choose', '{"audio_text": "tell me about yourself", "options": ["tell me about the job", "tell me about yourself", "tell me about your salary", "tell me about the company"], "answer": "tell me about yourself"}'::jsonb, 7, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'revision_conversation_lesson_1'), 'select_correct_verb', '{"sentence": "She ___ very well in the interview and got the job.", "answer": "performed", "options": ["performed", "perform", "performs", "performing"]}'::jsonb, 8, 2, 10, true);

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'revision_conversation'), 'revision_conversation_lesson_2', 'La visite chez le médecin', 2, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'revision_conversation_lesson_2'), 'flashcard', '{"front": "symptoms", "back": "symptômes"}'::jsonb, 1, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'revision_conversation_lesson_2'), 'flashcard', '{"front": "treatment", "back": "traitement"}'::jsonb, 2, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'revision_conversation_lesson_2'), 'translate_sentence', '{"prompt": "J''ai les mêmes symptômes depuis une semaine.", "answer": "I have had the same symptoms for a week.", "hint": "mêmes = same, depuis = for/since"}'::jsonb, 3, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'revision_conversation_lesson_2'), 'fill_in_the_blank', '{"sentence": "The doctor asked me to describe my ___.", "answer": "symptoms", "options": ["symptoms", "furniture", "books", "weather"]}'::jsonb, 4, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'revision_conversation_lesson_2'), 'word_reorder', '{"words": ["I", "have", "had", "a", "cough", "for", "two", "weeks"], "answer": "I have had a cough for two weeks"}'::jsonb, 5, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'revision_conversation_lesson_2'), 'true_or_false', '{"statement": "Pointing and saying mal ici helps a doctor understand where you feel pain.", "answer": true, "explanation": "Mal ici means it hurts here and is one of the most useful phrases at a medical appointment"}'::jsonb, 6, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'revision_conversation_lesson_2'), 'listen_and_choose', '{"audio_text": "I need a repeat prescription", "options": ["I need a new doctor", "I need a repeat prescription", "I need an X-ray", "I need a sick note"], "answer": "I need a repeat prescription"}'::jsonb, 7, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'revision_conversation_lesson_2'), 'type_what_you_hear', '{"audio_text": "treatment", "answer": "treatment", "hint": "what a doctor prescribes to help you recover"}'::jsonb, 8, 2, 10, true);

INSERT INTO lessons (id, module_id, slug, title_al, display_order, lesson_type, xp_reward, is_published)
VALUES (gen_random_uuid(), (SELECT id FROM modules WHERE slug = 'revision_conversation'), 'revision_conversation_lesson_3', 'La situation administrative', 3, 'standard', 50, true);

INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'revision_conversation_lesson_3'), 'flashcard', '{"front": "reference number", "back": "numéro de référence"}'::jsonb, 1, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'revision_conversation_lesson_3'), 'flashcard', '{"front": "to appeal", "back": "faire appel / contester"}'::jsonb, 2, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'revision_conversation_lesson_3'), 'translate_sentence', '{"prompt": "Je n''ai pas reçu ma convocation, que dois-je faire ?", "answer": "I have not received my summons, what should I do?", "hint": "convocation = summons/notice"}'::jsonb, 3, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'revision_conversation_lesson_3'), 'fill_in_the_blank', '{"sentence": "Please quote your ___ number when contacting us.", "answer": "reference", "options": ["reference", "cooking", "colour", "garden"]}'::jsonb, 4, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'revision_conversation_lesson_3'), 'word_reorder', '{"words": ["I", "need", "help", "understanding", "this", "official", "letter"], "answer": "I need help understanding this official letter"}'::jsonb, 5, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'revision_conversation_lesson_3'), 'true_or_false', '{"statement": "You can request an interpreter at an official appointment in France.", "answer": true, "explanation": "You have the right to request an interpreter for official administrative proceedings in France"}'::jsonb, 6, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'revision_conversation_lesson_3'), 'listen_and_choose', '{"audio_text": "you can appeal this decision", "options": ["you must accept this decision", "you can appeal this decision", "you should ignore this letter", "you need a lawyer immediately"], "answer": "you can appeal this decision"}'::jsonb, 7, 2, 10, true);
INSERT INTO exercises (id, lesson_id, mold_type, content, display_order, difficulty, xp_value, is_published) VALUES (gen_random_uuid(), (SELECT id FROM lessons WHERE slug = 'revision_conversation_lesson_3'), 'select_correct_verb', '{"sentence": "She ___ all her paperwork and submitted it on time.", "answer": "gathered", "options": ["gathered", "gather", "gathers", "gathering"]}'::jsonb, 8, 2, 10, true);
